### ISSUE TITLE
Failure to parse “catch where” expression

### ISSUE THREAD

**Issue by Frizlab** [apple/swift-syntax#1040]
### Issue Kind

Parse of Valid Source Failed

### Source Code

```swift
import Foundation
do {}
catch where (error as NSError) == NSError() {}
```

### Description

The source parses correctly with the old parser, I get the following error with the new one:
```
toto.swift:3:7: error: expected expression in pattern
catch where (error as NSError) == NSError() {}
      ^
<unknown>:0: error: new parser has failed consistency checking; please see errors above
```
Toolchain version: `org.swift.57202210271a` on macOS.

**Comment by ahoppen** [comment]
rdar://101815618
