### ISSUE TITLE
Classify Macros As PoundKeyword-like Entities

### ISSUE THREAD

**Issue by CodaFi** [apple/swift-syntax#1044]
### Description

Macros for builtin directives (#line, #file, etc) used to be classified as pound directives and pound keywords, but we now see a # and an identifier.

**Comment by ahoppen** [comment]
rdar://102213800

**Comment by ahoppen** [comment]
These built-in directives are now implemented as macros in the standard library. So, it’s correct now that these are colored as `#` followed by an identifier.
