### ISSUE TITLE
Default `init` style from `SwiftBasicFormat` looks unfamiliar

### ISSUE THREAD

**Issue by stevapple** [apple/swift-syntax#1115]
### Description

Currently `SwiftBasicFormat` defaults to format initializer declaration as `init (…)` and `init ?(…)`.

This is diverged from the common practice as well as the [Swift book](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html).

eg. https://github.com/apple/swift-syntax/blob/aeb2ff511cd0a4e37f794a93004f55fb03be2633/Sources/SwiftSyntaxBuilder/generated/ResultBuilders.swift#L93-L95

### Steps to Reproduce

```swift
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftBasicFormat

class CodeGenerationFormat: BasicFormat {
  override var indentation: TriviaPiece { .spaces(indentationLevel * 2) }
}

let sourceFile = SourceFile {
  StructDecl("public struct SimpleError: Error") {
    VariableDecl("private let code: Int")
    InitializerDecl("""
      public init?(errorCode: Int) {
        guard errorCode > 0 else { return nil }
        self.code = errorCode
      }
      """)
  }
}

print(sourceFile.formatted(using: CodeGenerationFormat()))
```

Output:

```swift
public struct SimpleError: Error {
  private let code: Int
  public init ?(errorCode: Int) {
    guard errorCode > 0 else { 
      return nil 
    }
    self.code = errorCode
  }
}
```

**Comment by ahoppen** [comment]
rdar://103011540

**Comment by ahoppen** [comment]
I don’t think this is something we need to fix. `BasicFormat` is not something that’s intended to be fully-accurate formatter - if it was, there would be no need for formatter packages anymore. Instead the goal of `BasicFormat` is to provide a formatting of the file that compiles (e.g. has a space between `public` and `init`) and that’s readable by humans.

I’ll use this bug report to add that sort of documentation of non-goals to `BasicFormat`. If we’ve got a good alternative (e.g. swift-format), we should probably underscore the SwiftBasicFormat module altogether.

---

@allevato Do you think it would be possible to add a static function (or something of the sort to swift-format) that takes a completely unformatted syntax tree that might even be missing required newlines and spits out a formatted version of the source file, still as a syntax tree? I tried

```swift
extension SwiftFormatter {
  public static func format(syntax: SourceFileSyntax, configuration: Configuration = Configuration(), operatorTable: OperatorTable = .standardOperators) -> SourceFileSyntax {
    let context = Context(
      configuration: configuration,
      operatorTable: operatorTable,
      findingConsumer: nil,
      fileURL: URL(fileURLWithPath: "source"),
      sourceFileSyntax: syntax,
      source: syntax.description,
      ruleNameCache: ruleNameCache
    )
    let pipeline = FormatPipeline(context: context)
    return pipeline.visit(Syntax(syntax)).cast(SourceFileSyntax.self)
  }
}
```

but if I throw that on the tree generated by SwiftSyntaxBuilder above, I get the following, so swift-format is not inserting the required newlines here.
```swift
public struct SimpleError: Error {private let code: Intpublic init?(errorCode: Int) {
  guard errorCode > 0 else { return nil }
  self.code = errorCode
}}
```

Interestingly if I first run it through SwiftBasicFormat to get the required newlines and then through swift-format as follows, it also doesn’t remove the space in front of the `?`.

```swift
let a = sourceFile.formatted(using: CodeGenerationFormat())
print(SwiftFormatter.format(syntax: a.cast(SourceFileSyntax.self)))
```
