### ISSUE TITLE
Misleading documentation for regenerating source code

### ISSUE THREAD

**Issue by hborla** [apple/swift-syntax#1133]
### Description

The [documentation for generating source files from gyb](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftSyntax/Documentation.docc/ChangingSwiftSyntax.md#regenerating-files) provides these instructions:

> To invoke build-script.py to regenerate source code, run
> 
> `$ ./build-script.py generate-source-code --toolchain /Path/To/Toolchain`
>
> where `/Path/To/Toolchain` can point either to the `XcodeDefault.xctoolchain` installed with Xcode, or to a [toolchain downloaded from swift.org](https://www.swift.org/download/).

However, if you pass in the path to a `.xctoolchain`, build-script will throw an exception:

```
~ ./build-script.py generate-source-code --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
** Generating gyb Files **
** Done Generating gyb Files **
** Running code generation **
Traceback (most recent call last):
  File "./build-script.py", line 987, in <module>
    main()
  File "./build-script.py", line 983, in main
    args.func(args)
  File "./build-script.py", line 732, in generate_source_code_command
    run_code_generation(
  File "./build-script.py", line 373, in run_code_generation
    check_call(swiftpm_call, env=env, verbose=verbose)
  File "./build-script.py", line 122, in check_call
    subprocess.check_call(cmd, cwd=cwd, env=env, stderr=subprocess.STDOUT)
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/bin/swift'
```

It seems you actually need to pass `<path-to-xctoolchain>/usr` to `./build-script.py generate-source-code`. When I do that, generating source code succeeds.

### Steps to Reproduce

Follow the instructions in the documentation at https://github.com/apple/swift-syntax/blob/main/Sources/SwiftSyntax/Documentation.docc/ChangingSwiftSyntax.md#regenerating-files

**Comment by ahoppen** [comment]
rdar://103218416

**Comment by ahoppen** [comment]
That's right. IIRC some/most documentation actually points to the `usr` subdirectory but this one has been missed, apparently. Updating it in https://github.com/apple/swift-syntax/pull/1138

**Comment by hborla** [comment]
Thank you!
