### ISSUE TITLE
Make CodeBlockItemListSyntax expressible by string literal

### ISSUE THREAD

**Issue by bradfol** [apple/swift-syntax#1165]
### Description

For the Syntax Builder it would be very convenient to be able to do something like the following to create a `CodeBlockItemList` from one multi-line string:

```
CodeBlockItemList("""
  let one = object.methodOne()
  let two = object.methodTwo()
""")
```

The `FunctionDecl` currently has behavior that allows for something similar, where it can parse the `CodeBlock` body of the function as well as the declaration:

```
FunctionDecl("""
func aFunction() {
  let one = object.methodOne()
  let two = object.methodTwo()
  // ...
}
""")
```
But I can't find a way to create a `CodeBlockItemList` from a multiline string otherwise.

**Comment by ahoppen** [comment]
rdar://103618439

**Comment by StevenWong12** [comment]
Hi @ahoppen, could you please assign this issue to me? I've already started to work with it recently.

**Comment by StevenWong12** [comment]
Thank you @kimdv!

**Comment by bradfol** [comment]
I did find a bit of a workaround that I've been using, which is to rely on the interpolation string conversion for `SourceFileSyntax`

```
let sourceFile: SourceFile = """
    let one = object.methodOne()
    """
```

**Comment by ahoppen** [comment]
I should have probably commented on this issue at some point, sorry. 

The current idea is that you don't create a `CodeBlockItemList` from one big string literal but every item from its own string literal. You should be able to do the following

```swift
CodeBlockItemList {
  "let one = object.methodOne()"
  "let two = object.methodTwo()"
}
```

I'm happy to change that but it would be good to see a motivating example that wouldn't work with the result builder on `CodeBlockItemList` before we make another node expressible by string literals

**Comment by bradfol** [comment]
> `CodeBlockItemList` from [...] every item from its own string literal

That would be great!

**Comment by ahoppen** [comment]
Great. I just renamed the issue and all that would need to be done for this is to make `CodeBlockItemListSyntax` conform to `SyntaxExpressibleByStringInterpolation`.

**Comment by ahoppen** [comment]
In the meantime what you can do is the following

```swift
CodeBlockItemListSyntax {
  DeclSyntax("let one = object.methodOne()")
  DeclSyntax("let two = object.methodTwo()")
}
```
