### ISSUE TITLE
`ReturnStmtSyntax("text.count")` makes a fatal error when the `return` keyword is missing

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1239]
### Issue Kind

Parser Crash

### Source Code

```swift
ReturnStmtSyntax("text.count")
```

### Description

The `return` is missing and when using this in the SyntaxBuilder it just fails with 

```
Swift/UnsafeBufferPointer.swift:313: Fatal error
FAIL: Source generation using SwiftSyntaxBuilder failed
```

it would be nice with a propper error message stating that the `return` is missing

**Comment by ahoppen** [comment]
rdar://104293148

**Comment by bnbarham** [comment]
We've decided to remove expressible by string literal on most of these nodes and not fatal error in the general case. For the code generation in swift syntax we'll have something like a constructor with `validating:` and that can keep being a fatal error + add in diagnostics there.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/1290 has fixed this and we now return a `ReturnStmtSyntax` that has syntax errors instead of `fatalError`ing.
