### ISSUE TITLE
Bad diagnostics for bogus effects specifier before arrow or brace in function 

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1262]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
func foo() bogus -> Int {}
() bogus reasync -> Int
```

### Description

Instead of using `at` to check for the `->` or `{`, we should check whether we can recover to it on the same line, possibly reducing the recovery precedence when parsing function types because they could be followed by an identifier.

**Comment by ahoppen** [comment]
rdar://104621275

**Comment by Rajveer100** [comment]
Hi @ahoppen, so with the grinding going on `swift compiler` already, I am also looking forward to contributing towards other apple repos like this one, so is there any additional required setup specifically for repos apart from `swift compiler,` as well as other potential ones which I could help and solve issues.

**Comment by StevenWong12** [comment]
Hi @ahoppen, I've just started investigating this issue. I ran the parse cli to print the diagnosics for the code snippet above and I got the following diagnostics

```
1 │ func test() bogus -> Int {}
  ∣            ╰─ error: consecutive statements on a line must be separated by ';'
```

From my understanding, it should produce a more useful diagnostics message for that e.g.

```
1 │ func test() bogus -> Int {}
  ∣            ╰─ error: unknown effect specifier
```

Have I got that right? 

Thanks in advance!

**Comment by ahoppen** [comment]
Yes, exactly. 

The first step would be to get it to produce something like the following by improving recovery inside there parser itself

```
1 │ func test() bogus -> Int {}
  ∣            ╰─ error: unexpected code 'bogus' in function declaration
```

As a second step you can then improve the diagnostic to `unknown effect specifier 'bogus'` in the diagnostic generator.

**Comment by StevenWong12** [comment]
Great! Thanks for your advice. I am about to try it out and hope this will be my first contribution to this repo!

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/1381
