### ISSUE TITLE
When getting a source location during macro resolution, everything is optional

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1309]
### Description

When using a macro context to get a source location during macro resolution, the source location itself is optional, and so is every property in the structure. That seems a bit much.

I'd suggest making just the source location optional (since you could pass an `Expr` from elsewhere) and then all the properties can be non-optional. I might also suggest having a `macroSourceLocation` property that's non-optional, since you presumably always know the macro's location!

**Comment by ahoppen** [comment]
rdar://104979208

**Comment by ahoppen** [comment]
I think this is a duplicate of https://github.com/apple/swift-syntax/issues/1525, which has been fixed.

**Comment by grynspan** [comment]
Agreed!
