### ISSUE TITLE
Macro expansions allow a space (or even newline) between `#` and macro name, as well as `@` and attribute name

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1395]
### Issue Kind

Other

### Source Code

```swift
# myMacroName
```

```swift
#
myMacroName
```

```swift
@ MyAttribute
func foo() {}
```

```swift
@
MyAttribute 
func foo() {}
```

### Description

The above examples parse as macro expansion or attribute but shouldn’t be valid. We need to check that the `#` or `@` doesn’t contain trailing trivia and the identifier doesn’t contain leading trivia to parse a macro expansion/attribute.

**Comment by ahoppen** [comment]
rdar://106464071

**Comment by TiagoMaiaL** [comment]
@ahoppen Is it possible to assign this issue to me? I'm already working on it on my free time.

**Comment by Matejkob** [comment]
Is it steel an issue? 
![Uploading Screenshot 2024-04-05 at 1.01.48 PM.png…]()

**Comment by ahoppen** [comment]
No, this was fixed by https://github.com/apple/swift-syntax/pull/2466. Thanks for noticing 👍🏽
