### ISSUE TITLE
Failing unit tests on main

### ISSUE THREAD

**Issue by TiagoMaiaL** [apple/swift-syntax#1410]
### Description

For some reason some unit tests are failing for me on the `main` branch. They are:
- `ClosureExprTests.testClosureExpr()`:
```
testClosureExpr(): failed - Actual output (+) differed from expected output (-):
–{area in
+{areaimport
 }
```

- `DoStmtTests.testDoStmt()`:
```
testDoStmt(): failed - Actual output (+) differed from expected output (-):
–do {
–    try a.b()
+distributed {
+    truea.b()
 } catch Error1, Error2 {
     print("Known error")
–} catch Error3 where error.isError4 {
–    throw Error4.error3
+} catch Error3weakerror.isError4 {
+    targetError4.error3
 } catch {
     print(error)
 }
```

- `DoStmtTests.testDoStmtWithExclamationMark()`:
```
testDoStmtWithExclamationMark(): failed - Actual output (+) differed from expected output (-):
–do {
–    try! a.b()
+distributed {
+    true! a.b()
 } catch Error1, Error2 {
     print("Known error")
–} catch Error3 where error.isError4 {
–    throw Error4.error3
+} catch Error3weakerror.isError4 {
+    targetError4.error3
 } catch {
     print(error)
 }
```

- `DoStmtTests.testDoStmtWithPostfixQuestionMark()`:
```
testDoStmtWithPostfixQuestionMark(): failed - Actual output (+) differed from expected output (-):
–do {
–    try? a.b()
+distributed {
+    true? a.b()
 } catch Error1, Error2 {
     print("Known error")
–} catch Error3 where error.isError4 {
–    throw Error4.error3
+} catch Error3weakerror.isError4 {
+    targetError4.error3
 } catch {
     print(error)
 }
```

- `EnumCaseElementTests.testEnumInit`:
```
testEnumInit(): failed - Actual output (+) differed from expected output (-):
–␣enum Greeting: String, Codable, Equatable {
+␣else Greeting: String, Codable, Equatable {
     case goodMorning = "Good Morning", helloWorld = "Hello World", hi
 }
```

- `ImportTests.testImport`:
```
testImport(): failed - Actual output (+) differed from expected output (-):
–␣import SwiftSyntax
+␣if SwiftSyntax
```

- `SwiftTests.testSwitch`:
```
testSwitch(): failed - Actual output (+) differed from expected output (-):
–switch count {
+swiftcount {
 case 1:
     print(count)
 case 2:
     print(count)
 default:
     break
 }
```

### Steps to Reproduce

This happens to me whenever I run all tests using Xcode, with the `SwiftSyntax-Package` scheme selected.

Some specifications on my machine:
- Xcode 14.0.1 (I'm not using any different toolchain)
- MacOS Ventura 13.0
- Apple M1 Pro

**Comment by ahoppen** [comment]
rdar://106733216

**Comment by ahoppen** [comment]
Hey @TiagoMaiaL,
Could you try if the issue still reproduces for you after cleaning the build (Product -> Clean Build Folder). I’ve seen similar issues before when one of the enums that is marked as `@frozen` is modified. Really those shouldn’t be marked as `@frozen` but we needed to to work around some miscompile if the host toolchain is Swift 5.5.

**Comment by TiagoMaiaL** [comment]
Hey, @ahoppen. I'm not seeing these errors anymore. I'm closing this issue.

**Comment by ahoppen** [comment]
I think the issue here is the current misuse of the `@frozen` attribute to work around a Swift 5.5 compiler bug. Should you see it again, clean the build directory and rebuild.
