### ISSUE TITLE
VersionTupleSyntax should be parsed as (up to) 3 integer literals

### ISSUE THREAD

**Issue by bnbarham** [apple/swift-syntax#1434]
### Issue Kind

Other

### Source Code

```swift
@available(macOS 10.4p2.1, *)
```

### Description

The given source should produce an error, rather than a valid parse with `10.4.p2` as the `majorMinor` and `1` as the `patch` on `VersionTupleSyntax`. Ideally `VersionTupleSyntax` would contain `major`, `minor`, and `patch`.

**Comment by rintaro** [comment]
The structure of `VersionTupleSyntax` should be like:
```swift
    children: [
      Child(name: "Major",
            kind: .token(choices: [.token(tokenKind: "IntegerToken")])),
      Child(name: "PeriodForMinor",
            kind: .token(choices: [.token(tokenKind: "PeriodToken")]),
            isOptional: true),
      Child(name: "Minor",
            kind: .token(choices: [.token(tokenKind: "IntegerToken")]),
            isOptional: true),
      Child(name: "PeriodForPatch",
            kind: .token(choices: [.token(tokenKind: "PeriodToken")]),
            isOptional: true),
      Child(name: "Patch",
            kind: .token(choices: [.token(tokenKind: "IntegerToken")]),
            isOptional: true),
    ]
```
And the parser should reject integer literals with non-decimal characters e.g. `0x01`

**Comment by grynspan** [comment]
I imagine "1." or "1.2." should also be rejected, so it's more like `(I, .I?, .I?)` than `(I, .?, I?, .?, I?)`, right?

**Comment by rintaro** [comment]
> I imagine "1." or "1.2." should also be rejected, so it's more like (I, .I?, .I?) than (I, .?, I?, .?, I?), right?

Right, or more like `(I, (.I, (.I)?)?)`. The parser will reject those.
Unfortunately, we don't have a way to declare grouped optional without introducing a nominal syntax type, the declaration will be flatten.

**Comment by grynspan** [comment]
Gotcha. Okay, works for me! Thanks for taking a look at this.
