### ISSUE TITLE
Rewrite `build-script.py` in Swift

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1465]
`build-script.py` is the only remaining Python file in SwiftSyntax. It would be nice to rewrite it in Swift so the only language used in SwiftSyntax is Swift (+ a tiny bit of C in `Sources/_InstructionCounter`).

**Comment by ahoppen** [comment]
rdar://107372272

**Comment by kimdv** [comment]
I have been thinking a bit here.
What do you think of we make a "swift-syntax-build-cli" package, just like code gen.
It uses the argument parser and have all the needed functionality as build-script.put

Then we move all the code gen into this package.

This package will in the future contain all the tooling needed for swift syntax. Formatting, test, code gen, verify code and so on.

**Comment by ahoppen** [comment]
Yes, that was essentially my idea. I think it might still be worthwhile to keep `CodeGeneration` as a separate executable just so you don’t need to build swift-syntax to run the newly written build-script.
