### ISSUE TITLE
`BasicFormat` doesn't add spaces between attributes

### ISSUE THREAD

**Issue by stevapple** [apple/swift-syntax#1504]
### Description

When using `AttributeListBuilder`, the build result (formatted by `BasicFormat`) doesn't have spaces between each attributes, which is ill-formed in Swift.

### Steps to Reproduce

```swift
let builder = AttributeListSyntax {
  AttributeSyntax("@inlinable")
  AttributeSyntax("@discardableResult")
}
print(builder) // @inlinable@discardableResult
```

**Comment by ahoppen** [comment]
rdar://107787207

**Comment by stevapple** [comment]
It also fails to add the space between an attribute and the declaration, eg.
```swift
let import = ImportDeclSyntax(attributes: [.attribute("@_exported")], path: [.init(name: "MyModule")])
print(import) // @_exportedimport MyModule
```

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/1569
