### ISSUE TITLE
Missing default paren tokens for `FunctionCallExprSyntax`

### ISSUE THREAD

**Issue by stevapple** [apple/swift-syntax#1506]
### Description

A `FunctionCallExprSyntax` usually come with left and right parens. Even if there could be no parens (with trailing closure instead), adding parens in such case is still legal in Swift.

To make `SwiftSyntaxBuilder` easier to use, we'd better provide default values for the two parens, and let the user opting out if they want.

### Steps to Reproduce

```swift
let builder = FunctionCallExprSyntax(calledExpression: ExprSyntax("print")) {
  TupleExprElementSyntax(expression: "Hello, world!".makeLiteralSyntax())
}
print(builder) // print"Hello, world!"
```

**Comment by ahoppen** [comment]
rdar://107787420

**Comment by stevapple** [comment]
@ahoppen I wonder if it's too verbose to create a new issue for `poundKeyword` from `IfConfigClauseSyntax`, which is slightly different. The value can only be `.poundIfKeyword()` there, so we have no reason not to add a default value.

**Comment by ahoppen** [comment]
There is the `FunctionCallExprSyntax(callee:)` initializer that does exactly what you want. You are calling the code-generated initializer that we still need for completeness sake (e.g. if you need to specify unexpected tokens). The fix here would probably be to add documentation to the code-generated initializer that pointes you to `FunctionCallExprSyntax(callee:)`.

---

`IfConfigClauseSyntax` is also used for the `#elseif` and `#else` clauses, so it’s expected that you need to manually specify `#if`.

**Comment by stevapple** [comment]
> There is the `FunctionCallExprSyntax(callee:)` initializer that does exactly what you want. You are calling the code-generated initializer that we still need for completeness sake (e.g. if you need to specify unexpected tokens).

I believe I’ve seen default token values provided in this kind of initializers? Wonder if adding a default value will really break anything, since the parser always passes the full set of parameters.

> `IfConfigClauseSyntax` is also used for the `#elseif` and `#else` clauses, so it’s expected that you need to manually specify `#if`.

Thanks for clarifying! It makes sense:)

**Comment by stevapple** [comment]
After investigating the generator detail I decided to close this — if we want to achieve this we may need to tweak the handling logic of `TokenChoice`, which is somehow not worth the price.
