### ISSUE TITLE
Generate doc-comment for syntax node initializers

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1598]
For each initializer of a Syntax node, we should be generating a doc comment that documents each parameter with the first line of that parameter’s description.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108643353

**Comment by Matejkob** [comment]
Hi there!

I would love to work on this issue.

I wonder about a few things:
1. Just to confirm, the goal of this task is to generate documentation for initializers like the one below in `ClassDeclSyntax`, correct?
```swift
public init(
    leadingTrivia: Trivia? = nil,
    _ unexpectedBeforeAttributes: UnexpectedNodesSyntax? = nil,
    attributes: AttributeListSyntax? = nil,
    _ unexpectedBetweenAttributesAndModifiers: UnexpectedNodesSyntax? = nil,
    modifiers: ModifierListSyntax? = nil,
    _ unexpectedBetweenModifiersAndClassKeyword: UnexpectedNodesSyntax? = nil,
    classKeyword: TokenSyntax = .keyword(.class),
    _ unexpectedBetweenClassKeywordAndIdentifier: UnexpectedNodesSyntax? = nil,
    identifier: TokenSyntax,
    _ unexpectedBetweenIdentifierAndGenericParameterClause: UnexpectedNodesSyntax? = nil,
    genericParameterClause: GenericParameterClauseSyntax? = nil,
    _ unexpectedBetweenGenericParameterClauseAndInheritanceClause: UnexpectedNodesSyntax? = nil,
    inheritanceClause: TypeInheritanceClauseSyntax? = nil,
    _ unexpectedBetweenInheritanceClauseAndGenericWhereClause: UnexpectedNodesSyntax? = nil,
    genericWhereClause: GenericWhereClauseSyntax? = nil,
    _ unexpectedBetweenGenericWhereClauseAndMemberBlock: UnexpectedNodesSyntax? = nil,
    memberBlock: MemberDeclBlockSyntax,
    _ unexpectedAfterMemberBlock: UnexpectedNodesSyntax? = nil,
    trailingTrivia: Trivia? = nil 
)
```
2. When you mention "(...) each parameter with the first line of that parameter’s description." am I correct in interpreting that "parameter's description" refers to `Child.getter:documentation` (assuming that the `child.description` has been renamed to `child.documentation`)?
3. If we are to utilize `Child.getter:documentation`, how would we determine "the first line" in this context? Considering that the `documentation` property is an optional String type, how can we define "the first line"? Perhaps we should use the entirety of the documentation property?
4. Are we including documentation for the `leadingTrivia`, `trailingTrivia` and all "unexpected*" parameters?

**Comment by ahoppen** [comment]
> 1. Just to confirm, the goal of this task is to generate documentation for initializers like the one below in `ClassDeclSyntax`, correct?

Yes, exactly

> 2. When you mention "(...) each parameter with the first line of that parameter’s description." am I correct in interpreting that "parameter's description" refers to `Child.getter:documentation` (assuming that the `child.description` has been renamed to `child.documentation`)?

Exactly. Unfortunately most children don’t have documentation but for the ones that do, it would be great do show it in the initializer.
> 3. If we are to utilize `Child.getter:documentation`, how would we determine "the first line" in this context? Considering that the `documentation` property is an optional String type, how can we define "the first line"? Perhaps we should use the entirety of the documentation property?

I would do the following:
- If the child’s documentation is `nil`, don’t generate an entry in the doc comment for that parameters, since we don’t have anything to show for it
- If the child’s documentation is not `nil`, use something like the following to get the first line and just show that.

```swift
extension StringProtocol {
  var firstLine: Self.SubSequence {
    if let firstNewline = self.firstIndex(where: { $0.isNewline }) {
      return self[..<firstNewline]
    } else {
      return self[...]
    }
  }
}
```

> 4. Are we including documentation for the `leadingTrivia`, `trailingTrivia` and all "unexpected*" parameters?

Adding documentation for `leadingTrivia` and `trailingTrivia` would make sense to me. I don’t think there’s any point in generating documentation for the `unexpected*` parameters. They are fairly self-explaining once you’ve grasped the concept of unexpected nodes and if you didn’t you most likely don’t care about them. So they would just produce clutter.
