### ISSUE TITLE
FixItApplier is not applying all Fix-Its

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1600]
### Description

FixItApplier is not applying all Fix-Its

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179887421
https://github.com/apple/swift-syntax/pull/1549#discussion_r1169231555

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108652253

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/2226
