### ISSUE TITLE
Wrong Fix-Its applied for `_unavailableFromAsync` attribute 

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1606]
### Description

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179886392
Test case `testUnavailableFromAsync`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108655875

**Comment by TiagoMaiaL** [comment]
@ahoppen, @kimdv I would like to start working on this issue. Can I get assigned to it?

It's not clear to me what the `fixedSource` should be, as I'm not acquainted with the `@_unavailableFromAsync` attribute.

**Comment by kimdv** [comment]
You can read the proposal here: https://github.com/apple/swift-evolution/blob/main/proposals/0340-swift-noasync.md

The fixed source should be `@_unavailableFromAsync(message: "abc")`

Right now it is `@_unavailableFromAsync(message: "" = "abc") `

**Comment by kimdv** [comment]
So I think if you just consume the `=` then you are good to go 😁

**Comment by mininny** [comment]
It seems like this was now resolved 👍 https://github.com/apple/swift-syntax/pull/1733
