### ISSUE TITLE
`:` is not applied in the correct place for function signature Fix-It

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1608]
### Description

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179896824
Test case `testInvalid13`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108656824

**Comment by TiagoMaiaL** [comment]
I want to start working in this issue. Is it ok if I get assigned to it? cc: @ahoppen @kimdv

**Comment by ahoppen** [comment]
It’s yours now. Thanks for looking into it.

In my opinion the key here is to detect that we are missing a type annotation and checking whether the internal parameter name starts with an uppercase letter, which usually indicates that it is meant to be a type name. We are already doing something similar here

https://github.com/apple/swift-syntax/blob/d14176d74bff98aa877bbf284a8bccd4bb02c833/Sources/SwiftParser/Types.swift#L551

**Comment by TiagoMaiaL** [comment]
I think we can close this issue 🎉 

Thank you for your assistance, @ahoppen!
