### ISSUE TITLE
Space is not balanced around `=` for Fix-Its

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1609]
### Description

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179900668
Test case `testTypealias6`

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179892965
Test case `testDiagnoseInitializerAsTypedPattern8a`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108656827
