### ISSUE TITLE
Bad diagnostic for let foo: [Int] []

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1610]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
let foo: [Int] []
```

### Description

This currently produces the following. We should be suggesting to add a `=` if a variable declaration is followed by an expression on the same line without a `=` in between.

```
1 │ let foo: [Int] []
  │               ╰─ error: consecutive statements on a line must be separated by ';'
```

rdar://108623515

**Comment by whiteio** [comment]
@ahoppen Hey could I be assigned to this please?
