### ISSUE TITLE
Add newline after `}` to separate from declarations

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1612]
### Description

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179899781
Test case `testSwitch2`

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179900425
Test case `TrailingSemiTests`
It would be nice to also offer a newline as that is properly what the developer wants.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108667014
