### ISSUE TITLE
`10e10` is not emitted as an invalid version tuple

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#1613]
### Description

https://github.com/apple/swift-syntax/pull/1549#discussion_r1179886829

Test case `testVersionParsing`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108668026

**Comment by TTOzzi** [comment]
Hello @kimdv @ahoppen ! 👋👋
May I be assigned to it?

**Comment by TTOzzi** [comment]
Thank you!
