### ISSUE TITLE
Wrong diagnostics for ternary expression when only the colon is missing

### ISSUE THREAD

**Issue by whiteio** [apple/swift-syntax#1624]
### Description

When diagnostics are generated for ternary expressions where the `:` is missing but both of the first and second choice expressions are present, the incorrect diagnostic message is used and the wrong Fix-It is applied.

### Steps to Reproduce

Example: 
```swift
foo ? 1 2
```

This results in the following diagnostic message and Fix-It:
```
expected ':' and expression after '? ...' in ternary expression
```
```swift
foo ? 1 : <#expression#>2
```

As the expression isn't missing in the example I expected the following diagnostic message and Fix-It:
```
expected ':' after '? ...' in ternary expression
```
```swift
foo ? 1 : 2
```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108750446
