### ISSUE TITLE
Rename `AccessPathSyntax` to `ImportPathSyntax`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1632]
Address this Fix-It.

https://github.com/apple/swift-syntax/blob/2179d9fe6335c54e2fb13419c1186ac549d407c2/CodeGeneration/Sources/SyntaxSupport/DeclNodes.swift#L33

Also rename any properties named `accessPath`. To keep existing clients building, provide a type alias that maps `AccessPathSyntax` to `ImportPathSyntax` and deprecated methods for `accessPath` to SwiftSyntaxCompatibility.swift

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108812214

**Comment by whiteio** [comment]
@ahoppen Is it ok if I work on this one?

**Comment by ahoppen** [comment]
That would be great
