### ISSUE TITLE
`ArrayExprSyntax` initializer that takes an array of `ExprSyntax`

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1674]
### Description

Constructing an `ArrayExprSyntax` from a Swift array of arbitrary `ExprSyntax` values is a bit of a pain. Right now, we do silly dances like:

```swift
let exprs: [ExprSyntax] = ...
let exprString = exprs.lazy
  .map(\.trimmedDescription)
  .joined(separator: ", ")
return ExprSyntax("[\(raw: exprString)]").as(ArrayExprSyntax.self)
```

Having a convenience initializer that inserts commas and necessary trailing trivia would make this much nicer.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://109483386

**Comment by gibachan** [comment]
Is it okay for me to handle this issue?

**Comment by kimdv** [comment]
Hi @grynspan! 

Would you be able to achieve your request with the result builder initialiser of `ArrayExprSyntax`

Maybe something like

```swift
ArrayExprSyntax {
          for item in [1, 2, 3, 4] {
              ArrayElementSyntax(expression: ExprSyntax("\(raw: item)"))
          }
      }
```

**Comment by ahoppen** [comment]
> Is it okay for me to handle this issue?

Sure, I assigned it to you.

> Would you be able to achieve your request with the result builder initialiser of `ArrayExprSyntax`
> 
> Maybe something like
> 
> ```swift
> return ArrayExprSyntax {
>     for item in [1, 2, 3, 4] {
>         ArrayElementSyntax(expression: ExprSyntax("\(raw: item)"))
>     }  
> }
> ```

To speak on @grynspan’s behalf: The motivating example here is where you already have an `[ExprSyntax]`. You could do the following but that seems kind dumb

```swift
ArrayExprSyntax {
  for element in arrayElements {
    element
  }
}
```
