### ISSUE TITLE
Inconsistent naming of properties for retrieving a generic parameter clause on decl nodes

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift-syntax#1678]
### Description

All applicable declaration nodes except `EnumDeclSyntax` use `genericParameterClause`. The respective property of `EnumDeclSyntax` is called `genericParameters`.

#### Environment 

93e905ce326457acee1d485cb0150616b92e3eae

**Comment by TTOzzi** [comment]
Hello @ahoppen @kimdv !
Could you please assign me to this task?
I plan to change the `genericParameters` of `EnumDeclSyntax` to `genericParameterClause` uniformly and keep the existing `genericParameters` with a deprecated annotation.

**Comment by TTOzzi** [comment]
Thank you kimdv! 😃
