### ISSUE TITLE
Parser should emit a single diagnostic if both open and close quote are missing from string literal

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1691]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
@_expose(Cxx, baz) func foo() {}
```

### Description

From https://github.com/apple/swift-syntax/pull/1688/files#r1201105564

In the above example the parser produces two diagnostics: One for the missing opening `"` before `baz` and one for the missing closing `"` after `baz`. It should emit a single diagnostic instead that offers to add both.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://109685043

**Comment by kimdv** [comment]
Go for it @TTOzzi 🙌

**Comment by TTOzzi** [comment]
Thank you! 😉
