### ISSUE TITLE
Fail to run CodeGeneration

### ISSUE THREAD

**Issue by StevenWong12** [apple/swift-syntax#1707]
### Description

After #1672 was merged, running CodeGeneration emits the following error:
`'codegeneration': product 'SwiftBasicFormat' required by package 'codegeneration' target 'generate-swiftsyntax' not found in package 'swift-syntax'.`

### Steps to Reproduce

run 
```shell
swift run --package-path CodeGeneration generate-swiftsyntax Sources
```

or just open CodeGeneration in Xcode

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://109872946

**Comment by kimdv** [comment]
Have you tried to delete locale caches and build folder?
I had a problem once, but deleting `.build` and `.swiftpm` it worked to resolve locally

**Comment by StevenWong12** [comment]
Yeah, I've tried to delete `.build` and `.swiftpm` in the `CodeGeneration` directory. But the problem remains.

**Comment by ahoppen** [comment]
To be clear, did you try deleting `CodeGeneration/.build` and `CodeGeneration/.swiftpm`? I’m not seeing the issue on top `main`.

**Comment by StevenWong12** [comment]
Yeah, that's exactly what I tried.

**Comment by StevenWong12** [comment]
I've re-clone the repo, then the problem is solved. Maybe some strange cache problems.🥲

**Comment by ahoppen** [comment]
OK, weird. Glad to see it resolved though.
