### ISSUE TITLE
Parsing fails if line break between enum case element name and parameter clause

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift-syntax#1709]
### Issue Kind

Parse of Valid Source Failed

### Source Code

This errors out without good reason (with both the new and legacy parsers):
```swift
enum E {
  case a
    (Int)
}
```

Similarly formatted function/subscript parameter lists parse fine.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://109913549

**Comment by AnthonyLatsis** [comment]
Out of curiosity, why are GitHub issues duplicated in the internal issue tracker?

**Comment by ahoppen** [comment]
It just makes it a lot easier for us to keep track of them if all issues are in a single issue tracker and to schedule/prioritize issues.

**Comment by ahoppen** [comment]
I think all that needs changing here is to remove `allowStartOfLine: false` in https://github.com/apple/swift-syntax/blob/707c6172558d86758b1c9be1d6eaff7c9cbf22dd/Sources/SwiftParser/Declarations.swift#L914.

I also don’t see a reason why the opening parenthesis needs to be on the same line as the case name.

**Comment by AnthonyLatsis** [comment]
Thank you for tending to these issues at such an impressive rate, Kim!
