### ISSUE TITLE
Inconsistent naming scheme for the elements of tuple-like syntax nodes

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift-syntax#1713]
### Description

`TupleExprSyntax.elementList` vs. `TupleTypeSyntax.elements`. I realize I am being pedantic but I also see no good reason to name them differently. No preference for a particular name, but perhaps worth noting that `ArraySyntaxExpr` uses `elements` and `FunctionTypeSyntax` uses `arguments`, i.e., without "list".

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://109978803

**Comment by ahoppen** [comment]
Thank you for these bug reports about naming inconsistencies, @AnthonyLatsis. I really appreciate them.

**Comment by AnthonyLatsis** [comment]
Ah btw do we *want* it to be `arguments`, and not `parameters`, for `FunctionTypeSyntax`?

**Comment by AnthonyLatsis** [comment]
#1720
