### ISSUE TITLE
Children naming inconsistencies between similar/dual syntax nodes

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift-syntax#1721]
### Description

* `GenericParameterClauseSyntax.genericParameterList` vs. `GenericArgumentClauseSyntax.arguments`. Following the plural noun trend, I would expect the former to be named `parameters`.
* `AvailabilityConditionSyntax.availabilitySpec` vs. `AvailabilityEntrySyntax.availabilityList` (both have the same type).
* `OriginallyDefinedInArgumentsSyntax.platforms` vs.  `BackDeployedAttributeSpecListSyntax.versionList` (both have the same type).

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://110170164

**Comment by TTOzzi** [comment]
> `GenericParameterClauseSyntax.genericParameterList` vs. `GenericArgumentClauseSyntax.arguments`. Following the plural noun trend, I would expect the former to be named `parameters`.

I agree. I share the same opinion 🙂 

> `AvailabilityConditionSyntax.availabilitySpec` vs. `AvailabilityEntrySyntax.availabilityList` (both have the same type).

According to the previously mentioned plural noun trend, 'availabilitySpecs' seems appropriate.

> `OriginallyDefinedInArgumentsSyntax.platforms` vs. `BackDeployedAttributeSpecListSyntax.versionList` (both have the same type).

Similarly, 'platforms' seems more fitting in this case as well.
