### ISSUE TITLE
Represent `swift` and `compiler` compilation conditions with separated node

### ISSUE THREAD

**Issue by StevenWong12** [apple/swift-syntax#1764]
### Description

https://github.com/apple/swift-syntax/pull/1574#discussion_r1178082913

Just to remind myself about that.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://110571334

**Comment by ahoppen** [comment]
We discussed this last week and actually decided that we don’t want to add special nodes for these directives. The Interpretation of these compilation conditions should be performed in the `IfConfig` library.

**Comment by StevenWong12** [comment]
Ah, I see. When the `SwiftIfConfig` is ready, I can help revert the change of adding `CanImportExprSyntax` and move the corresponding test cases there.

Btw, do you think we should still keep [this pr](https://github.com/apple/swift-syntax/pull/1766)?
