### ISSUE TITLE
"Any.Type" in header always outputs as "Any .Type" with an extra space

### ISSUE THREAD

**Issue by ssly1997** [apple/swift-syntax#1815]
### Description

![246605376-4701d2cb-b77b-4c23-a427-aa7612a528f1](https://github.com/apple/swift-syntax/assets/101865961/fc7c6eda-9b3e-4ccf-9e00-2b32a8db50bd)
---
"Any.Type" in header always outputs as "Any .Type" with an extra space.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://111017063
