### ISSUE TITLE
Change `name` property of `Child` in `CodeGeneration` to be lowercase

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1901]
It’s a little counter-intuitive that the `name` property of `Child` needs to be uppercase because AFAICT we are always using it as lowercase. Change the argument to be lowercase. The generated code should not change.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://112178612

**Comment by Matejkob** [comment]
I love this idea! May I try to develop it?

**Comment by ahoppen** [comment]
Definitely!
