### ISSUE TITLE
MemberAccessExprSyntax.name/.declNameArguments should be a single IdentifierExprSyntax

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1924]
### Description

`MemberAccessExprSyntax` consists of a `base` expression and a `name` (and optional `declNameArguments`.) Seems like it should really be composed of a `base` and an `IdentifierExprSyntax` (which contains both a name and declNameArguments already.) This would make it somewhat easier to splice off the `base` expression.

**Comment by grynspan** [comment]
`DeclNameSyntax` isn't an `ExprSyntax` though, which poses problems if you're e.g. using a `SyntaxRewriter` to strip `base` off of a node. (Which is a thing I need to do.)

Arguably, `IdentifierExprSyntax` is the exact same thing as a `DeclNameSyntax` though. Harmonize the two types?

**Comment by ahoppen** [comment]
This was fixed by one of my recent renames of syntax nodes.
