### ISSUE TITLE
Rename `generate-swiftsyntax` to `generate-swift-syntax`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1935]
`generate-swiftsyntax` generates the entire `swift-syntax` package, not just the `SwiftSyntax` module. Thus, it should be named `generate-swift-syntax`.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://112672032

**Comment by arirays** [comment]
Can I contribute to the project?

**Comment by Matejkob** [comment]
I was going through issues and encountered this one; I believe it was fixed #2073.

**Comment by ahoppen** [comment]
Oh, yes. Thanks for noticing.
