### ISSUE TITLE
Shorter-hand string interpolation for literals

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1963]
### Description

Let's say I have a node `x` that I want to convert to a string literal and include in another node I'm constructing using string interpolation. I don't want trivia, so I'll probably say:

```swift
let y: ExprSyntax = "blahBlah(\(literal: x.trimmedDescription))"
```

Or whatever. It'd be nice to have some conveniences around this pattern. Perhaps:

```swift
let y: ExprSyntax = "blahBlah(\(trimmedLiteral: x))"
```

Although I bet we could do better.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113059358

**Comment by ahoppen** [comment]
The uses cases for this seem very limited outside of macros like `#stringify`. Since the suggested alternative isn’t much longer and hard to get wrong, this is not something we are planning to add unless a huge number of use cases come up.
