### ISSUE TITLE
Create new section for attribute nodes in docc index 

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1973]
[SwiftSyntax.md](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftSyntax/Documentation.docc/generated/SwiftSyntax.md) has sections for expression, declaration etc. nodes. A large portion of the nodes in the Miscellaneous section concern attributes. We should have a section for all the attributes nodes. All nodes from the [AttributeNodes.swift](https://github.com/apple/swift-syntax/blob/main/CodeGeneration/Sources/SyntaxSupport/AttributeNodes.swift) file should end up in that section.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113236772

**Comment by Matejkob** [comment]
I can do that if you don't mind
