### ISSUE TITLE
Rename `file` parameter of `SourceLocationConverter` initializers to `fileName`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1974]
`file` is ambiguous because it could also refer to the file contents. `fileName` is clearer.

Also rename the corresponding property. We should provide deprecated initializers that still accept `file`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113236778

**Comment by natikgadzhi** [comment]
I'll work on this if that's okay! Expect a PR in a few hours.
