### ISSUE TITLE
Rename `isAt*` functions in `SwiftParser` to `at*`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1976]
We have the `at(_: TokenSpec)` functions to check if we are at a token but some of the more complex `at` functions like `isAtStartOfPostfixExprSuffix` start with `isAt`. To be consistent, we should remove `is` here.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113237445

**Comment by natikgadzhi** [comment]
@ahoppen, I'll grab these next — expect a PR by Friday ;)

**Comment by natikgadzhi** [comment]
### First findings

There are _quite a few functions and properties` that follow `isAt*` notation. Focusing on just the functions, here's the list that I'll rename first:

- [ ] `Lexer.Cursor.isAtStringInterpolationAnchor` — private, so I'll rename it and change any spots where it's invoked. Deprecating the existing function should not be necessary.
- [ ] `Lexer.Cursor.isAtEscapedNewline` — same as above.
- [ ] `Parser.Lookahead` has two fileprivate functions `isAtStartOfPostfixExprSuffix` and `isInBindingPatternPosition` — I think it's best to rename both of them so the code in that particular extension is consistent. It would be weird to have `atStartOfPostfixExprSuffix` and `isIn*`. 
- [ ] `Parser.isAtPythonStyleInheritanceClause`
- [ ] In `Parser/Statements.swift` we have `Parser.Lookahead` extension with `isAtStartOfSwitchCase`, `isStartOfStatement`, `isStartOfConditionalSwitchCases`. 
   - These are not market as private, so I _think_ we should keep the original version and deprecate it.
   - Should I rename `isStartOf*` as well for consistency? 

### Questions
In some cases, there are `isAt*` funcs side by side with `isSomethingElse`, and it's tempting to go over them as well, so the language of the API is consistent, but I also want to keep the scope of this manageable and easy to review. 

Does the list above look good for the first PR, @ahoppen? I'm happy to support the migration to the new notation further if we will choose to.
