### ISSUE TITLE
For children of syntax nodes that are `TokenSyntax`, list the kinds of tokens it can contain

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#1987]
For example `DeclReferenceExprSyntax.baseName` should have a comment saying the following (token choices can be generated using `GrammarGenerator`): 

```
For syntax trees generated by the parser, this is guaranteed to be one of the following token kinds:
- `<identifier>`
- 'self'
- 'Self'
- 'init'
- <dollarIdentifier>
- <binaryOperator>
- <integerLiteral>
```

For children that only have one token kind, like `StructDeclSyntax.structKeyword` it should say something like the following

```
For syntax trees generated by the parser, this is guaranteed to be the following kind: 'struct'
```

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113297164

**Comment by natikgadzhi** [comment]
I don't mean to be greedy, but I'm knee-deep in docs and figuring out how to work in code generation already, so might as well take on that, unless anyone beats me to it 🙃.

**Comment by ahoppen** [comment]
Please, fix as many issues as you want. I’m happy for every one of them.

**Comment by natikgadzhi** [comment]
I'm still on it — after working on code generation for a bit, I know where and what to tweak, and expect to get this solved in a few days.

**Comment by kimdv** [comment]
Just for us to remember: As mentioned in #2153 we could generate 
```swift
The `actor` keyword.
```

For the keyword child on an Actor. We could add the rule that if there is no documentation provided, we generate it.
