### ISSUE TITLE
Rename `Lookahead.is*` function to `at*`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2001]
Similar to https://github.com/apple/swift-syntax/issues/1976. There are a few `is*` functions in `Lookahead` like `isStartOfGetSetAccessor`. For consistency these should be named `at*`, e.g. `atStartOfGetSetAccessor`.

**Comment by ahoppen** [comment]
@natikgadzhi In case you can be tempted to do this one as well.

**Comment by natikgadzhi** [comment]
Yep, I can do that today, feel free to assign it to me.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113567634
