### ISSUE TITLE
Incorporate Doug’s macro examples in swift-syntax/Examples

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2026]
https://github.com/DougGregor/swift-macro-examples is a great collection of macros. We should move them to the Examples folder in swift-syntax to give them more exposure and make sure they build with recent swift-syntax versions.

**Comment by Matejkob** [comment]
Love it! 🚀💙

**Comment by Matejkob** [comment]
To make sure: our goal is not only to add a link to those examples but literally move the hole code and adjust it to global standards, isn't it?

**Comment by kimdv** [comment]
I think it's moving the code. 
If they are inside the Examples we actually try to compile it. Ensures that they work too, if we change things 

Do you want this task, I can assign it to you 🙌

**Comment by Matejkob** [comment]
On one hand, I've been experimenting with Swift macros quite a bit, and I have a few ideas on how to standardize building macros and so forth. However, I don't want to be overly ambitious and take on too many tasks for myself. 😅

**Comment by kimdv** [comment]
It's just moving them from Doug's repo to this one 😁

**Comment by Matejkob** [comment]
How about we take it a step further? I've noticed some unresolved issues and PRs on Doug's repo. It might be a good idea to not only transfer the code but also undertake a slight refactor. This way, we ensure everything is not only in one place but also optimized, clear, and up-to-date with the project's standards. I believe this could provide even more value to our community. What do you think?

**Comment by kimdv** [comment]
Defiantly it could do that! 

I'll assign you if you are up to it

**Comment by ahoppen** [comment]
Improving those examples would be a great task as well. I would prefer to do it in two different steps, though: First, just copy the examples and make sure they build inside the examples folder. We can then discuss improvements to them in follow-up PRs.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113567655

**Comment by Matejkob** [comment]
I'm on it :>
