### ISSUE TITLE
How to import macros using methods other than SPM 

### ISSUE THREAD

**Issue by ssly1997** [apple/swift-syntax#2028]
### Description

I'm trying to import macro functionality using CocoaPods, but Xcode is giving an error:
```
External macro implementation type 'XXX' could not be found for macro 'XXX'; the type must be public and provided by a macro target in a Swift package, or via '-plugin-path' or '-load-plugin-library'. 
```
I haven't found any articles about '-plugin-path' or '-load-plugin-library
How can I resolve this?

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113567662

**Comment by ssly1997** [comment]
> I see that you also posted this question on the Swift forums. Does the solution suggested there work? https://forums.swift.org/t/how-to-import-macros-using-methods-other-than-spm/66645/2

It seems ineffective; macro expansion has already been achieved, but compilation still results in errors.
![image](https://github.com/apple/swift-syntax/assets/101865961/ee95fe31-66f8-4a8a-98eb-72360a781eab)

**Comment by ahoppen** [comment]
Since this is most certainly a configuration problem with CocoaPods and not a swift-syntax bug, let’s continue discussing it in the forums.

**Comment by ssly1997** [comment]
> Since this is most certainly a configuration problem with CocoaPods and not a swift-syntax bug, let’s continue discussing it in the forums.

Regarding '-plugin-path' or '-load-plugin-library,' could you provide me with some suggestions? It appears to be related to Swift macros functionality, but there is no official documentation available
