### ISSUE TITLE
Validate that the docc documentation archive doesn’t have issues in CI

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2081]
We should generate a docc archive in CI and make sure that it doesn’t show any warnings.

rdar://110990240

**Comment by natikgadzhi** [comment]
That would likely mean using `swift-docc-plugin` and triggering docc build with `swift package generate-documentation`, right?

I've played around with DocC a bit, I can do that. I would argue that we should move `format.py` into `Scripts/format.py` and put the DocC builder in there, too. And we should use SSWG projects as a reference — some of them build docc bundles in CI I think.

**Comment by ahoppen** [comment]
Ah, sorry, I forgot to assign this to myself: I’ve got a draft PR for this up: https://github.com/apple/swift-syntax/pull/2096. 

It just depends on the CI nodes being updated to macOS 13 so that we can use Swift regex for that script.

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2096 is merged
