### ISSUE TITLE
Enable the ordered imports rule in swift-format

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2136]
AFAIK swift-format has a rule to force import statements to be ordered lexicographically. But that rule doesn’t appear to be enabled in this repository. W should enable it.

**Comment by natikgadzhi** [comment]
Mind if I use this one as a reason to read more about swift-format rules and set it up?

**Comment by ahoppen** [comment]
Sure, go ahead.

**Comment by Matejkob** [comment]
I recall that in one of the PRs with @kimdv  and @ahoppen , we discussed how sometimes we skip the `return` keyword in the codebase, and sometimes we don't. At that time, `swift-format` didn't have a rule for this, but that's changed. There's now a rule to omit the `return` keyword whenever possible. 

So the question is, do we want to adopt this rule?

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://114841762

**Comment by ahoppen** [comment]
It would definitely be interesting to see what the code looks like with the implicit return rule enabled. I think I commented somewhere that I‘m personally not a fan of omitting the return but consistency is more important than my personal preference.

**Comment by natikgadzhi** [comment]
#2145 adds `OrderedImports`, but I'll push up another commit to it with implicit returns so we can take a look at the code and see if we like it.

Interesting finds: 
- `swift-format` will not complain if you make a typo in a rule name. I made a typo `OrderedImpora` and ran `./format.py` and it didnt' output anything, and didn't change any files, of course — would be nice to have a warning form `swift-format`. I'll file an issue and make a PR.
- `swift-format dump-configuration` dumps the default json config, but does not explain what each rule does. It would be nice to have a comment with each of the config settings that summarizes how it works. Again, easy PR probably.

**Comment by natikgadzhi** [comment]
Follow-up swift-format issues:
- Comments in dump-configuration: https://github.com/apple/swift-format/issues/606
- Detect mistakes in the Rules configuration: https://github.com/apple/swift-format/issues/607

**Comment by natikgadzhi** [comment]
So, the ordered imports rule PR is merged in (#2145). Since omitting returns is unlikely to get merged, I think we should close this issue, @ahoppen.

Both follow-up issues in `swift-format` have pending pull requests, and I think those are going to get merged in later this week, too. 🥳

**Comment by kimdv** [comment]
Thanks @natikgadzhi 😁

Resolved by #2145
