### ISSUE TITLE
Enable `MemoryLayoutTest` in CI/release builds

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2170]
`MemoryLayoutTest` is currently only built in debug mode, which means that we don’t test it in CI, where we build swift-syntax in release mode. 

We should also enable it in release mode. The expected memory layout sizes might be different in release mode. In that case, we need to have two different `expected` dictionaries.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://115176290

**Comment by Matejkob** [comment]
I believe that PR #2175 resolves the issue, but something seems to have gone wrong with the auto-close, hasn't it?
