### ISSUE TITLE
Mark Version 509.0.0 as "Latest"

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-syntax#2210]
### Description

Since version 509.0.0 was released a few days ago, so we need to mark it as the latest version.

<img width="387" alt="Screenshot 2023-09-18 at 10 21 31 AM" src="https://github.com/apple/swift-syntax/assets/49780321/d6c36fc2-2e05-438b-95b3-eb43e877f31b">

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://115644851

**Comment by ahoppen** [comment]
Oh, I swear I set the checkbox when creating the release tag. Thanks for reporting this, should be fixed now.
