### ISSUE TITLE
Change `parseIncrementally` to return a struct instead of a tuple

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#2267]
From https://github.com/apple/sourcekit-lsp/pull/857#discussion_r1349304038

> Is there a reason `Parser.parseIncrementally` returns a tuple instead of a dedicated struct? Seems like a single type would be easier to manage, and would help ensure you don't pass a mismatching syntax tree + lookahead ranges to `IncrementalParseTransition` (and would make it trivial to add any additional state later down the road if needed).

Like with all API changes, we need to see if we can do this in an API-compatible way. I think breaking the API here might be acceptable because the user base of this function should be fairly small, but an API-compatible way would definitely be preferred.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116599711

**Comment by kimdv** [comment]
@ahoppen I think this can be closed?

**Comment by ahoppen** [comment]
Oh, yes it can. Thanks for noticing.
