### ISSUE TITLE
Please add an example of how to use Swift Syntax with XcodeKit Source Editor Extensions

### ISSUE THREAD

**Issue by Eric-Catalyst** [apple/swift-syntax#2276]
### Description

The most natural use case for Swift Syntax would be parsing code being extracted and updated in an Xcode Source Editor Extension.  Please add an example of this case.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116782712

**Comment by ahoppen** [comment]
We do already have one: https://github.com/apple/swift-syntax/tree/main/EditorExtension 

Is this what you were looking for?

**Comment by ahoppen** [comment]
> Might be helpful to mention it in the main read me.

I don’t think that’s all too useful. There exists documentation of how to build an Xcode source editor extension and depending on swift-syntax should just be a matter of adding swift-syntax to your package dependencies. 

> Should this be a separate issue?

Thanks for noting. Fixing it in https://github.com/apple/swift-syntax/pull/2277

**Comment by Eric-Catalyst** [comment]
Thanks for your attention and assistance.
