### ISSUE TITLE
Main branch should have a `SwiftSyntax510` module

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-syntax#2279]
### Description

While it's suggested to use things like `#if canImport(SwiftSyntax509)` to target specific versions of SwiftSyntax, there's no way to support versions before 509 _and_ after 509 at the moment. A `SwiftSyntax510` module should allow libraries to be compatible with the `main` branch concurrently with 509, though.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://116922161

**Comment by Matejkob** [comment]
Shouldn't the `main` branch include both `SwiftSyntax510` and `SwiftSyntax511`, especially since we already have an official `release/5.10` branch?

**Comment by ahoppen** [comment]
> Shouldn't the `main` branch include both `SwiftSyntax510` and `SwiftSyntax511`, especially since we already have an official `release/5.10` branch?

Both should contain `SwiftSyntax510`. I’m not sure about `SwiftSyntax511` because we haven’t named the next release yet. Could be Swift 5.11 or Swift 6.0 and I don’t want to add `SwiftSyntax511` only to remove it in favor of `SwiftSyntax600`.

**Comment by Matejkob** [comment]
I've taken the liberty of preparing PRs for both the `main` and `release/5.10` branches, where I've introduced a new target: `SwiftSyntax510`.
