### ISSUE TITLE
Undeclared SwiftSyntaxMacroExpansion dependency on SwiftOperators

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-syntax#2287]
### Description

When building with `--explicit-target-dependency-import-check error`, swift-syntax fails to build due to the error: `error: Target SwiftSyntaxMacroExpansion imports another target (SwiftOperators) in the package without declaring it a dependency.`.

### Steps to Reproduce

`swift build --explicit-target-dependency-import-check error` on the 5.9 release.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117004722

**Comment by Matejkob** [comment]
I believe that Pull Request #2285 from @mbrandonw will resolve this issue.

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/2285
