### ISSUE TITLE
Add a new change that can replace a note

### ISSUE THREAD

**Issue by kimdv** [apple/swift-syntax#2298]
### Description

From https://github.com/apple/swift-syntax/pull/2286#discussion_r1359927684

>Hmm, it’s not easily possible in the current design where we assume all nodes for the Fix-It to already be present in the syntax tree so that we just need to flip the token presence. 

>I would say that it’s good enough for now but adding support for these kinds of Fix-Its might be useful in general. What we need for that is, IMO, a new `Fixit.Change` that takes a syntax node, a key path within that node and a replacement node, i.e. something like `case replace<NodeType, ChildType>(node: NodeType, path: KeyPath<NodeType, ChildType>, child: ChildType`) – and yes I see the irony of declaring a generic enum case here, you would need to come up with some design that actually compiles, I haven’t thought about it too much yet.

>I think this kind of Fix-It change might also be useful for macro authors. IIRC it came up once or twice but was never super important.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117082263

**Comment by kimdv** [comment]
Close in favour of https://github.com/apple/swift-syntax/issues/2205
