### ISSUE TITLE
accessor macro expansion doesn't remove initializer from stored property

### ISSUE THREAD

**Issue by mayoff** [apple/swift-syntax#2310]
Test code: [the AutoEnvironmentKey branch of my fork of swift-macro-examples](https://github.com/mayoff/swift-macro-examples/tree/AutoEnvironmentKey)

Toolchain: [the latest nightly, swift-DEVELOPMENT-SNAPSHOT-2023-02-15-a](https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2023-02-15-a/swift-DEVELOPMENT-SNAPSHOT-2023-02-15-a-osx.pkg) in Xcode 14.2 (14C18) on macOS 13.2.1 (22D68).

[SE-0389, Attached Macros](https://github.com/apple/swift-evolution/blob/main/proposals/0389-attached-macros.md#accessor-macros), says

> The expansion of an accessor macro that does not specify one of `willSet` or `didSet` in its list of names must result in a computed property. A side effect of the expansion is to remove any initializer from the stored property itself; it is up to the implementation of the accessor macro to either diagnose the presence of the initializer (if it cannot be used) or incorporate it in the result.

The `AutoEnvironmentKey` macro in the linked repo is an accessor macro that does not specify either `willSet` or `didSet`, and indeed it returns `get` and `set` accessors in its expansion. But swiftc does not remove the initializer. The `testAutoEnvironmentKey` test case demonstrates this. It uses this input syntax:

```
extension EnvironmentValues {
  @AutoEnvironmentKey
  public var myValue: String = "don't abuse macros"
}
```

and expects this output syntax:

```
extension EnvironmentValues {
  public var myValue: String {
    get { self[EnvironmentKey_for_myValue.self] }
    set { self[EnvironmentKey_for_myValue.self] = newValue }
}
  private enum EnvironmentKey_for_myValue: EnvironmentKey {
    static var defaultValue: String { "don't abuse macros" }
  }
}
```

but the actual expanded syntax is this:

```
extension EnvironmentValues {
  public var myValue: String = "don't abuse macros" {
    get { self[EnvironmentKey_for_myValue.self] }
    set { self[EnvironmentKey_for_myValue.self] = newValue }
}
  private enum EnvironmentKey_for_myValue: EnvironmentKey {
    static var defaultValue: String { "don't abuse macros" }
  }
}
```

Note that the initializer has not been removed from the actual expanded syntax.

**Comment by bnbarham** [comment]
Transferred over to swift-syntax - the issue here is solely in MacroSystem, which `assertMacroExpansion` uses. The compiler itself is fine (ie. it does remove the initializer).

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://117442713

**Comment by stephencelis** [comment]
It seems that this bug can lead to the execution of the wrong code, _i.e._ the original initializer instead of the macro-inserted code: https://github.com/apple/swift/issues/71070

**Comment by bnbarham** [comment]
The issue as described here was referring to the expansion from `MacroSystem`, which isn't used by the compiler (and was fixed in https://github.com/apple/swift-syntax/pull/2315). Yours seems to be the *compiler* not removing the initializer, which is separate.
