### ISSUE TITLE
Simplify Running Dev Utils Commands for Enhanced Developer Experience

### ISSUE THREAD

**Issue by Matejkob** [apple/swift-syntax#2341]
### Description

The process of executing formatting (also other) commands using SwiftSyntax development utilities has become a point of contention due to its complexity. The command:

```
swift run --package-path SwiftSyntaxDevUtils/ swift-syntax-dev-utils format
```

is lengthy and not easily memorized, which can deter its frequent use. This hampers the workflow efficiency.

Reflecting on the ease of the old `./format.py` command, there's a clear need for a more streamlined approach. The proposal for a root-level shell script that encapsulates the verbose command into a more manageable form is commendable. With such a script, developers could run a much simpler command:

```bash
./swift-syntax-dev-utils format
```

or 

```bash
./dev-utils format
```

**Implementation Goals:**
- Craft a shell script that acts as a gateway for the current complex commands.
- Make sure the script can accept and correctly pass through arguments to the SwiftSyntax development utilities. All commands should be handled; it would be beneficial to also handle `help` command.
- Update the project documentation to guide contributors on the usage of the new streamlined command.

Originally posted in a https://github.com/apple/swift-syntax/pull/2334#discussion_r1385402678

**Comment by Matejkob** [comment]
I guess it could be cool `good first issue`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://118137372
