### ISSUE TITLE
Needed: variant of `assertMacroExpansion()` that does not use XCTest

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#2400]
### Description

Test targets that use swift-testing instead of XCTest need some way to work with this function; let's add a throwing equivalent that can be used without any dependency on a specific testing library.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://119519713

**Comment by ahoppen** [comment]
Implemented in https://github.com/apple/swift-syntax/pull/2647
