### ISSUE TITLE
Too much skipping after invalid token in `for` element name

### ISSUE THREAD

**Issue by rintaro** [apple/swift-syntax#2406]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
for var elem? in arr { }
```

### Description

This results diagnostics:
```
test.swift:1:13: error: expected 'in' and expression in 'for' statement
1 │ for var elem? in arr { }
  │             ├─ error: expected 'in' and expression in 'for' statement
  │             ╰─ error: unexpected code '? in arr' in 'for' statement
2 │ 
```
And in the parsed syntax tree `? in arr ` part is parsed as `CodeBlockItemSyntax.unexpectedBeforeLeftBrace`

**Comment by rintaro** [comment]
Desired diagnostic would be, _for this specific case_, to fix it like:
```swift
for case var elem? in arr
```
but at least, skipping should stop at `in`

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://119742421
