### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by smy088** [apple/swift-syntax#2462]
Hi,

I'm trying to get started with devcontainers but I can not use the [cpp devcontainer image](https://github.com/devcontainers/images/tree/main/src/cpp) because its base image (base-ubuntu in my case) does not support a recent enough version for me (I need a recent version of gcc, currently only available in ubuntu lunar).

So, I tried authoring both a custom base-ubuntu and a custom cpp template. I'm struggling with using base-ubuntu as the base of my cpp template. I must be missing something. Does the devcontainer template package in ghcr.io need to be built to a docker image and hosted elsewhere?

The whole point of doing this in two templates is that cpp depend on some of the decontainer features being available from base-ubuntu (git, common).

Here is my repo and the most recent pull request smoke test, with trace output for devcontainer cli's up command: https://github.com/meastp/devcontainer-templates/actions/runs/5878222841/job/15939860188?pr=5

I suspect the problem is that I'm trying to reference the base-ubuntu image in src/cpp/Dockerfile:
```
FROM ghcr.io/meastp/devcontainer-templates/base-ubuntu:latest
```
I'm not sure how to solve this, if it should be supported or if I need to build the image out of band?

_Originally posted by @meastp in https://github.com/devcontainers/template-starter/issues/26_

**Comment by meastp** [comment]
hi - I solnedgang this by creating devcontainer image(s) instead. Have a look at meastp/images :)
