### ISSUE TITLE
DeclGroupSyntax should have introducerKeyword

### ISSUE THREAD

**Issue by ktoso** [apple/swift-syntax#2535]
### Description

It should be possible to `.as(DeclGroupSyntax.self)?.introducerKeyword` when writing macros in order to easily write diagnostics like "cannot be applied to **struct**"  etc.

Currently one has to do manual if/else of all the kinds we support

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://124247480
