### ISSUE TITLE
BasicFormat doesn't indent statement in `if` expression correctly

### ISSUE THREAD

**Issue by SimplyDanny** [apple/swift-syntax#2563]
The output of the code
```swift
let expr = """
    if a {
        print(1)
    }
    """
let meth = """
    func f(a: Bool) {
        \(raw: expr)
    }
    """ as DeclSyntax
print(meth.formatted())
```

is

```
func f(a: Bool) {
    if a {
    print(1)
    }
}
```

Notice that the `print(1)` statement is not indented correctly.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://125290309

**Comment by ahoppen** [comment]
This behaves as expected. Using the `raw` interpolation style, the effective string produced for `meth` is

```swift
func f(a: Bool) {
    if a {
    print(1)
}
}
```

This matches how raw string interpolation works for normal strings and you can see this if you print `meth` without formatting it. 

`BasicFormat` now detects that `print(1)` is already manually indented and will thus not adjust its indentation (the idea here is that you are able to manually indent parts of your source code and BasicFormat should only touch those that aren’t already formatted. It will thus not add another level of indentation to `print(1)`.

To fix this, you can change `expr` to be an `ExprSyntax` and not use the raw string interpolation style inside meth. With that you are in the smarter syntax-based string interpolation world, which will add the indentation of the line that contains the string interpolation anchor to the entire node you are inserting, adding 4 spaces to every line in `expr`.

```swift
let expr: ExprSyntax = """
  if a {
      print(1)
  }
  """
let meth = """
  func f(a: Bool) {
      \(expr)
  }
  """ as DeclSyntax
print(meth.formatted())
```

**Comment by SimplyDanny** [comment]
Good to know. Thank you for the explanation! I guess the general advise then is to work more with syntax objects and syntax builders instead of raw strings to get the full and proper support of the SwiftSyntax infrastructure.
