### ISSUE TITLE
Update CONTRIBUTING.md to include PR process / forking information

### ISSUE THREAD

**Issue by adammcarter** [apple/swift-syntax#2575]
### Description

Hi all, when making my first contribution (🎉) it wasn't quite clear on the process to create PRs within this repo - see the comment from here: https://github.com/apple/swift-syntax/issues/1936#issuecomment-2025867752 onwards in that thread.

From that conversation it was suggested to open an issue to update the CONTRIBUTING.md to include the steps for non-maintainers to open their very own PRs.

The information on this post: https://github.com/apple/swift-syntax/issues/1936#issuecomment-2025880317 from @Matejkob was super useful and would be good enough to copy and paste in to the CONTRIBUTING.md for any future travellers too IMO.

Thanks in advance!

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://125570301

**Comment by adammcarter** [comment]
PR opened here for this issue: https://github.com/apple/swift-syntax/pull/2577
