### ISSUE TITLE
Compiler crashes when build in release mode (Linux)

### ISSUE THREAD

**Issue by Buratti** [apple/swift-syntax#2668]
### Description

Tested on both Ubuntu and Amazon Linux 2.
Might be related to https://github.com/apple/swift-syntax/issues/2483.

### Steps to Reproduce

`docker run --rm -it swift:5.10.0-amazonlinux2`
`git clone https://github.com/apple/swift-syntax`
`cd swift-syntax`
`git checkout 510.0.2`
`swift build -c release`

Output:
`error: compile command failed due to signal 9 (use -v to see invocation)`

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://129223949

**Comment by Buratti** [comment]
Hi @ahoppen! I ran a few more tests. The issue is not related to swift-syntax. The compiler crashed because the container did not have enough memory reserved to it. Increasing the memory _"fixes"_ the issue.
