### ISSUE TITLE
trimming trivia nodes corrupts source ranges

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift-syntax#2687]
### Description

using the [`trimmed`](https://swiftinit.org/docs/swift-syntax/swiftsyntax/syntaxprotocol.trimmed) family of `SyntaxProtocol` methods corrupts the `ByteSourceRange`s when obtaining syntax classifications.

i was able to reproduce this on `510.0.2`, and on `600.0.0-prerelease-2024-06-12`.

### Steps to Reproduce

```swift
import SwiftIDEUtils
import SwiftParser
import SwiftSyntax

let text:String = """
@_documentation(metadata: blah)
public mutating
func f() {}
"""
let utf8:[UInt8] = .init(text.utf8)

var parser:Parser = utf8.withUnsafeBufferPointer { .init($0) }
let decl:DeclSyntax = .parse(from: &parser)

let function:FunctionDeclSyntax = decl.as(FunctionDeclSyntax.self)!

for span:SyntaxClassifiedRange in function.modifiers.trimmed.classifications
{
    let range:Range<Int> = span.range.offset ..< span.range.offset + span.range.length
    print(String.init(decoding: utf8[range], as: Unicode.UTF8.self))
}
```

```

publi
c
 mutatin
```

**Comment by ahoppen** [comment]
This behaves as intended. Running `trimmed` modifies the syntax tree to remove the leading and trailing trivia of the first and last token, respectively. The trimmed node should probably be detached from the original tree, which would make the behavior more obvious.

I would suggest that you do something like the following

```swift
let trimmed = function.modifiers.detached.trimmed
let trimmedBytes = trimmed.syntaxTextBytes
for span in trimmed.classifications {
    let range = span.range.offset ..< span.range.offset + span.range.length
    print(String.init(decoding: syntaxTextBytes[range], as: Unicode.UTF8.self))
}
```
