### ISSUE TITLE
Add GitHub Release (as a pre-release) for pre-release tags

### ISSUE THREAD

**Issue by liamnichols** [apple/swift-syntax#2688]
### Description

Hello, thank you for taking the time to tag pre-releases that follow semantic versioning, they're great in enabling us to test the newer versions of swift-syntax early on!

The only downside is that it is not easy to find them amongst the hundreds of snapshot/nightly tags in the GitHub UI:

<img width="765" alt="Screenshot 2024-06-18 at 20 08 24" src="https://github.com/apple/swift-syntax/assets/482871/8fe8beb4-e221-43a8-b095-4198cb8a49b0">

It would be great if we could consider publishing the latest tags (i.e `600.0.0-prerelease-2024-06-12`) as a pre-release on GitHub 🙏

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://130095695

**Comment by ahoppen** [comment]
I created https://github.com/apple/swift-syntax/releases/tag/600.0.0-prerelease-2024-06-12 just now. I’ll try and remember creating GitHub prereleases in the future.

**Comment by liamnichols** [comment]
Thanks @ahoppen ! 🙏
