### ISSUE TITLE
`final` should be classified as a `.contextualKeyword("final")` not `.identifier("final")`

### ISSUE THREAD

**Issue by valentinradu** [apple/swift-syntax#387]
Currently `final` is classified as `.identifier("final")` but should be `.contextualKeyword("final")`

**Steps to reproduce:**
```
final class SomeClass {  }
```
Parse the above and the `TokenSyntax.tokenKind` of `final` will be `.identifier("final")`. Should be `.contextualKeyword("final")`.

**Discussion here:**
https://forums.swift.org/t/why-is-final-parsed-as-an-identifier-value/57011/4

**Comment by ahoppen** [comment]
Tracking internally as rdar://92463926

**Comment by ahoppen** [comment]
Fixed in https://github.com/apple/swift/pull/58616.
