### ISSUE TITLE
[SR-14392] No such module 'MaterialComponents' only when archiving?

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#401]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14392      |
   |Radar             | None         |
   |Original Reporter | besart.haxhidema (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | CodeCompletion, Compiler, SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | besart.haxhidema (JIRA)      |
   |Priority          | Medium      |

   

   md5: 632482ec7a801dbde43c2d4492e5168d

  </details>

**Issue Description:**

I am trying to archive my app, but I get 'No such module 'MaterialComponents' error. The app runs on simulator and real device.

This is my ppod file:

**Uncomment the next line to define a global platform for your project# Uncomment the next line to define a global platform for your project# platform :ios, '10.0'**\*

**Comment the next line if you're not using Swift and don't want to use dynamic frameworks  use_frameworks!**  
  **\# Pods for Učiti Engleski**

**pod 'Firebase/Core'**

**pod 'Firebase/Database'**

**pod 'Firebase/Auth'**

**pod 'Firebase/Crash'**

**pod 'Google-Mobile-Ads-SDK','\~\>8.0'**

**pod 'MaterialComponents/Cards'**

**pod** **'OneSignal', '\>= 3.0.0', '\< 4.0'**  
**end**  
**target 'OneSignalNotificationServiceExtension' do** 

**\#only copy below line use_frameworks!**  
  **pod 'OneSignal', '\>= 3.0.0', '\< 4.0'end**

**Comment by kimdv** [comment]
@ahoppen I think we can close this one, as it looks like it's not related to SwiftSyntax.

**Comment by ahoppen** [comment]
Closing because this is not open source specific. Please report the bug through https://feedbackassistant.apple.com as mentioned above.

**Comment by Overcot** [comment]
Is this issue to be closed?) @ahoppen
