### ISSUE TITLE
[SR-13619] Using SwiftSyntax to parse a definition file, results in unknown declarations

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#403]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13619      |
   |Radar             | rdar://problem/69701608         |
   |Original Reporter | swiftuilab (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 57f6cbe2a43f7ef6bb506bf778d15230

  </details>

**Issue Description:**

Not sure if this is a bug, or a feature request, so I'm filing it as a bug for the moment.

I am using SwiftSyntax to parse a definition file (to be clear, I'm talking about the file generated by Xcode when you right click on a symbol and select "jump to definition").

For example, a stripped-down piece of the SwiftUI definition file looks like this:

``` java
public struct Binding<Value> {
  public var wrappedValue: Value { get nonmutating set }
  public var projectedValue: Binding<Value> { get }
}
```

The projectedValue variable is properly parsed as **VariableDeclSyntax**, but wrappedValue is parsed as **UnknownDeclSyntax.** The "set" part is what makes SwiftSyntax to not detect a variable.

This makes sense in a way, as that is not a valid syntax to use while writing code. However, in the context of the definition file it is ok. The color coding in Xcode also provides a hint, as the "nonmutating set" shows uncolored.

I tried to dig a little more, but I think the problem (if it is such), resides in the lib_InternalSwiftSyntaxParser.dylib library.

**Comment by ahoppen** [comment]
AFAICT the issue appears to be resolved, so I’m closing this issue. Please re-open it if you don’t agree.
