### ISSUE TITLE
[SR-13584] Make convenience methods returning an the value of an integer literal as Int and of floating literal as Float return an optional

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#405]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13584      |
   |Radar             | None         |
   |Original Reporter | vermont42 (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | vermont42 (JIRA)      |
   |Priority          | Medium      |

   

   md5: 14ad515b7c276d59a1dd762b567c3a4b

  </details>

**Issue Description:**

After the [PR](https://github.com/apple/swift-syntax/pull/239) for SR-11580 merged, there was consensus, based on feedback, that the new convenience methods `floatingValue` and `integerValue`, should be optional in order to prevent potential crashes. This story is for implementation of this change. There was additional feedback involving naming and genericity. Depending on PR-review feedback, this story may encompass implementation of these changes as well.

**Comment by ahoppen** [comment]
rdar://95634857

**Comment by ahoppen** [comment]
If anyone is interested in doing this: We would need to port the following code to Swift for the integer literal:

https://github.com/apple/swift/blob/15f7a28ff3fb6427438d3dcc9d2111fb82f85023/lib/AST/Expr.cpp#L1078-L1167

**Comment by kimdv** [comment]
@ahoppen I could be interested in this, if it's still needed.

**Comment by ahoppen** [comment]
Yes, I think this would still be great to have.
