### ISSUE TITLE
[SR-13126] `deinit` without braces results in 'unknown' node (shows up when parsing .swiftinterface files)

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#409]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13126      |
   |Radar             | rdar://problem/65192354         |
   |Original Reporter | schwa (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963875-f1d70992-8210-4a6c-800b-596de2ed4f4c.gz)

      
<details>
  <summary>Environment</summary>

Tested against release/5.3 of swift-syntax

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: af87e62f21e27dd8333ceb97a0b8d3a2

  </details>

**Issue Description:**

I have a test project using swift-syntax. Project can parse and dump a .swift file successfully. Same project cannot parse and dump a .swiftinterface file.

It would be super-useful to be able to parse .swiftinterface files too.

**Comment by CodaFi** [comment]
Resolved in the new parser by https://github.com/apple/swift-syntax/pull/716
