### ISSUE TITLE
[SR-11625] SyntaxRewriter crashes when called from a thread other than main

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#413]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11625      |
   |Radar             | None         |
   |Original Reporter | benpious (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

SwiftSyntax 0.50100.0, Xcode 11.1. Made a simple SwiftPM project, used generate-xcodeproj to make a project to open (double-clicking the Package.swift file did not produce a buildable project).

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9e3f668e7cbc4a6d8fd8813e5c6f08ad

  </details>

**Issue Description:**

I'm trying to create and use a SyntaxRewriter subclass from a thread other than main. I'm **not** sharing between threads, so it seems like it should be fine. However, I get an EXEC_BAD_ACCESS inside of SwiftSyntax. Here's some sample code that demonstrates the problem, which is adapted from the SwiftSyntax README's sample code:

``` java
let string = """

protocol P {
    var x: Int? { get set }
}


"""

let queue = DispatchQueue.global()
let sourceFile = try! SyntaxParser.parse(source: string)
let semaphore = DispatchSemaphore(value: 0)
queue.async {
    _ = Renamer().visit(sourceFile)
    semaphore.signal()
}
semaphore.wait()
print("done")
```

It crashes with an EXEC_BAD_ACCESS, typically in \`SyntaxRewriter.visitChildren()\`. Trying to print any variables in the debugger outputs "Trying to put the stack in unreadable memory at \<some memory address\>".

I can't reproduce this in an optimized build.

**Comment by Overcot** [comment]
I Guess the issue should be marked as resolved? Because in corresponding issues in JIRA all issues seems to be resolved

**Comment by ahoppen** [comment]
Dupe of https://github.com/apple/swift-format/issues/357
