### ISSUE TITLE
[SR-10174] Childen of a MemberDeclListSyntax are no longer typed

### ISSUE THREAD

**Issue by Jeehut** [apple/swift-syntax#420]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10174      |
   |Radar             | None         |
   |Original Reporter | @Jeehut      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 10.2, macOS 10.14.3.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 308b17bfa083679803f5f2d92c489f53

  </details>

**Issue Description:**

In the Swift 4.2 release, childen of a \`MemberDeclListSyntax\` type were typed, thus the following code was working:

 

``` java
let enumCaseDeclarations: [EnumCaseDeclSyntax] = enumDeclaration.members.members.children.compactMap { $0 as? EnumCaseDeclSyntax }
```

 

But after updating to Xcode 10.2 today, which includes the Swift 5.0 release, all \`children\` members are of type \`Syntax\` and casting to \`EnumCaseDeclSyntax\` fails, although that's the type I'm expecting here. You can find an example Swift file being parsed [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/Demo/Untouched/Demo/BartyCrouch.swift).

Why was this API changed to be less informative? And how am I supposed to cast it to the appropriate type going forward with the 5.0 release?

It would be great to get feedback soon, so I can make a Xcode 10.2 compatible release of my tool [BartyCrouch](https://github.com/Flinesoft/BartyCrouch). See also the appropriate line [here](#L18).

 

Thank you for your help in advance!

**Comment by ahoppen** [comment]
Closing this issue because the issue appears to be fixed. If you don’t agree, please re-open the issue.
