### ISSUE TITLE
[SR-9850] There's no obvious way to get content of a syntax node

### ISSUE THREAD

**Issue by dduan** [apple/swift-syntax#422]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9850      |
   |Radar             | None         |
   |Original Reporter | @dduan      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Improvement        |
   |Assignee          | @nkcsgexi      |
   |Priority          | Medium      |

   

   md5: 7a905c33db7bd997093527302f0f11ec

  </details>

**Issue Description:**

Each syntax node has a contentLength property, which does not count the length of trivia. It would be great to have a way to get the text corresponding to this content. Currently, achieving this task is not super easy.

 

@harlanhaskins @akyrtzi

**Comment by ahoppen** [comment]
Just going through some old bugs that are still open. Isn’t this implemented with `node.description`? I’m speculatively closing this. If this issue is about something that isn’t supported by the `description` property, please re-open it.
