### ISSUE TITLE
[SR-8800] Enhancing swift-syntax to allow #sourcelocation to appear in any location

### ISSUE THREAD

**Issue by johnno1962** [apple/swift-syntax#427]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8800      |
   |Radar             | None         |
   |Original Reporter | @johnno1962      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, SwiftSyntax    |
   |Labels            | Bug, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1857afa8697bcd58bd807f0a45bdf324

  </details>

**Issue Description:**

This arose out of the discussion on <https://github.com/apple/swift/pull/19347> which allows \#sourceLocation directives to occur in collections. Rather than have Syntax accept \#sourceLocation as an alternative for an array/dictionary element it was suggested perhaps Syntax should treat \#sourceLocation as trivia going forward.  
See <https://github.com/apple/swift/pull/19347#issuecomment-422882754>

**Comment by ahoppen** [comment]
Allowing `#sourceLocation` in more locations would require a Swift Evolution proposal. Closing this issue because SwiftSyntax behaves as expected.
