### ISSUE TITLE
[SR-10024] Add new TokenKinds for contextual keyword in libSyntax/SwiftSyntax

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#434]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10024      |
   |Radar             | None         |
   |Original Reporter | kitasuke (JIRA User)      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963158-30fdfdd1-44c8-4b43-a4f9-be4bc07bcef6.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, SwiftSyntax    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f6a7999be8142907c0d76093517b06c8

  </details>

**Issue Description:**

All contextual keyword's token kind is \`identifier\` for now, but I would like to have them as keyword kind instead.

For example, I was expecting to have \`weakKeyword\` for below variable declaration, but I got \`identifier("weak")\` in SwiftSyntax. In this context, it can tell keyword, not identifier.

Same thing happens to other contextual keywords as well.

 

``` java
@IBOutlet private weak var button: UIButton!
```

 

**Sample code:**

``` java
// sample.swift
class View {
 @IBOutlet private weak var button: UIButton!
}
```

``` java
 $swiftc -frontend -emit-syntax sample.swift  
```

 

**Expected:** 

``` java
"tokenKind":{"kind":"kw_weak"} 
```

**Actual:**

``` java
"tokenKind":{"kind":"identifier","text":"weak"}
```

**Environment:**

Xcode 10.2 beta 3 (10P99q)

Apple Swift version 5.0 (swiftlang-1001.0.63.8 clang-1001.0.43)  
Target: x86_64-apple-darwin18.2.0

**Comment by ahoppen** [comment]
rdar://95638944

**Comment by ahoppen** [comment]
Looks like `weak` in the example is now correctly classified as a contextual keyword.

```
~> cat /tmp/a.swift
class View {
 @IBOutlet private weak var button: UIButton!
}
~> ~/sbin/swift-frontend -frontend -emit-syntax /tmp/a.swift
…
{
    "kind": "contextual_keyword",
    "text": "weak"
},
...
```
