### ISSUE TITLE
[SR-9038] Swift Syntax requires the use of dynamic linking

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-syntax#442]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9038      |
   |Radar             | None         |
   |Original Reporter | tannernelson (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 4         |
   |Component/s       | SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9bbab7716cc05fa62a1f9472abf24ed4

  </details>

**Issue Description:**

Currently Swift Syntax vends a dynamic product (<https://github.com/apple/swift-syntax/blob/master/Package.swift#L8).>

This creates issues when trying to link a static executable that uses Swift Syntax. Is there any way this could be changed to a normal product?

**Comment by CodaFi** [comment]
This is no longer true as of #616. You can now consume SwiftSyntax and the SwiftParser as static libraries without any superfluous dependencies.
