### ISSUE TITLE
Support functional decomposition of code blocks

### ISSUE THREAD

**Issue by tachyonics** [apple/swift-syntax#470]
#### Description

Being able to decompose code blocks into separate functions can improve code readability and reuse.

#### Motivation

Allow developers to decompose code blocks into different functions.

#### Importance

This will allow for cleaner and more modular code.

Example:
https://github.com/amzn/smoke-framework-application-generate/blob/swift_syntax/Sources/SmokeFrameworkCodeGeneration/ServiceModelCodeGenerator%2BgenerateHandlerSelector.swift#L64

#### Alternatives Considered

I have tested this ability with the following change-
https://github.com/tachyonics/swift-syntax/commit/27c159b653fce0783aa612a56fa4d3e5fdda5a16

However I hadn't created a pull request on this change immediately as I am looking for guidance on if this change is a good idea, if there is some other way to achieve this or if this is the best way to incorporate it into the repository.

**Comment by ahoppen** [comment]
I think what you are asking for is exactly what is being fixed by https://github.com/apple/swift-syntax/pull/462, right?

**Comment by tachyonics** [comment]
Yes, exactly. Thanks for point that out.

I'll resolve this in favour of the change in #462.
