### ISSUE TITLE
add a filter-like API to SyntaxCollection

### ISSUE THREAD

**Issue by kelvin13** [apple/swift-syntax#592]
#### Description

right now, `SyntaxCollection` can only delete (or insert) one node at a time. because deletion and insertion invalidates indices, deleting many nodes at once is quadratic complexity. so `SyntaxCollection` should have a way to filter its children.

#### Motivation

source code generation involves detecting and removing template declarations from a source file, and replacing them with many generated variants of that declaration. so `SyntaxCollection`s that contain declarations need an API to efficiently remove and insert many children at once.

#### Importance

source code generation with existing quadratic APIs is still possible but could be very slow when many declarations are involved 

#### Alternatives Considered

i asked on [the swift forums](https://forums.swift.org/t/swiftsyntax-how-to-filter-list-items-out-of-list-syntax/59664) but no one was familiar enough with `swift-syntax` to suggest a workaround or way of removing/inserting children efficiently because the index type is opaque.

**Comment by ahoppen** [comment]
In the forums, I suggested using

```swift
class X: SyntaxRewriter {
  override func visit(_ list:MemberDeclListSyntax) -> Syntax {
      let filteredList:MemberDeclListSyntax = .init(list.filter({ _ in true }))
      return super.visit(filteredList)
  }
}
```

How would you like the API to look like? The only improvement I can think of would be to remove the need for `.init`, in which case we would end up with

```swift
class X: SyntaxRewriter {
  override func visit(_ list:MemberDeclListSyntax) -> Syntax {
      let filteredList:MemberDeclListSyntax = list.filter({ _ in true })
      return super.visit(filteredList)
  }
}
```

Is that what you are thinking of or are you suggesting something else?

**Comment by ahoppen** [comment]
rdar://98765082

**Comment by kelvin13** [comment]
so, as it turned out, the initializers that take an array of `[MemberDeclListItemSyntax]` were exactly what i needed, and i am now using them in [`swift-package-factory`](https://github.com/kelvin13/swift-package-factory/tree/master/Sources/Factory). i had to do some extra work to preserve attached doccomments when deleting the first attribute on a declaration, but i’m not sure if that warrants a library API. 

thinking back, the root causes of me filing this issue were documentation and toolchain-related, not a deficiency in API.

* the emphasis on `withFoo`-like APIs made me believe there was something about syntax nodes that makes unrolling them into arrays and rebuilding them from such fundamentally unsafe. so i did not trust `SyntaxFactory` to rebuild syntax from an array and give back the same result. better documentation would have helped here 

* i was using the august release of `swift-syntax`, but browsing docs [i had built](https://swiftinit.org/reference/swift-syntax) from june, so i did not know about new API or deprecating `SyntaxFactory`.

so i think this issue can be either closed or converted to a documentation issue because really the API i needed [exists already](https://github.com/apple/swift-syntax/pull/462) i just did not know about it. 

for what it is worth i did not think to rebuild my docs on swiftinit because i didn’t think this package was evolving very quickly because most apple `swift-x` packages do not have anyone actively working on them but now that i am browsing the history of this repo i see you are working on `swift-syntax` a lot so that is partially my fault.

**Comment by ahoppen** [comment]
Do you have any specific documentation in mind that would have helped you find the correct API?

**Comment by kelvin13** [comment]
basic API references would have helped me find the initializers and code completion would have gotten me the rest of the way there. 

an article or snippet demonstrating unpacking and repacking a list node (like [`AttributeListSyntax`](https://swiftinit.org/reference/swift-syntax/swiftsyntax/attributelistsyntax)) would have helped me understand that this was a valid way of processing syntax.

i have already pushed an [update](https://swiftinit.org/reference/swift-syntax) to swiftinit, so all that is needed is a short article or snippet demonstrating example usage.

**Comment by ahoppen** [comment]
Hi @kelvin13, 

we’ve now got API documentation of SwiftSyntax up: https://swiftpackageindex.com/apple/swift-syntax/main/documentation/swiftsyntax 

Do you think that would have helped you? If yes, do you want to close the issue. If not, we can keep it open and provide any documentation that would have helped you.

**Comment by kelvin13** [comment]
yes! merry christmas!
