### ISSUE TITLE
Round trip-failure for `"\(()`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#634]
### Issue Kind

Round-Trip Failure

### Source Code

```swift
"\(()

```

**Comment by ahoppen** [comment]
rdar://99103248

**Comment by omochi** [comment]
@ahoppen Would you like to close this? (and  #632)

**Comment by ahoppen** [comment]
Ah, yes. I thought they were auto-closed by the PR but looks like they weren’t. Thanks for keeping track of it.

Test case added by https://github.com/apple/swift-syntax/pull/649.
