### ISSUE TITLE
Round-trip failure with malformed struct

### ISSUE THREAD

**Issue by DougGregor** [apple/swift-syntax#678]
### Issue Kind

Round-Trip Failure

### Source Code

```swift
struct n#if@
```

**Comment by ahoppen** [comment]
rdar://99430621

**Comment by MEnnabah** [comment]
Couldn't reproduce this as a round-trip on main (`741b5c0`). I've added a test to cover this case #711.

**Comment by CodaFi** [comment]
Resolved by the merge of #711
