### ISSUE TITLE
Parse @differentiable attribute

### ISSUE THREAD

**Issue by DougGregor** [apple/swift-syntax#681]
### Issue Kind

Round-Trip Failure

### Source Code

```swift
@differentiable(reverse wrt,where T
```

**Comment by ahoppen** [comment]
rdar://99430632

**Comment by MEnnabah** [comment]
Can I give this bug a go? I'd like to fix a good first issue :)

**Comment by ahoppen** [comment]
Absolutely, [FixingBugs.md](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftParser/SwiftParser.docc/FixingBugs.md) contains some tips on how to get started. I am also currently updating CONTRIBUTING.md to contain more up-to-date instructions of how to run the tests [here](https://github.com/apple/swift-syntax/pull/693).

If you have any questions, don’t hesitate to ask.

**Comment by MEnnabah** [comment]
That's great @ahoppen! 

Actually I'm having some difficulties running the unit tests under [swift-syntax/Tests/SwiftParserTest](https://github.com/apple/swift-syntax/tree/main/Tests/SwiftParserTest).
I've asked a [more detailed question](https://forums.swift.org/t/a-new-swift-parser-for-swiftsyntax/59813/27) under Doug's post about in the forum.
