### ISSUE TITLE
If an attribute is put on a statement, the entire statement is classified as unexpected

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-syntax#714]
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
func test1() {
  #^TEST_1^#@s return
}
```
(from `testAttributesOnStatements`)

### Description

This should eat `@s` as unexpected tokens and parse `return` as a statement instead of complaining
```
Unexpected text '@s return' found in function
```

**Comment by ahoppen** [comment]
rdar://99594971

**Comment by CodaFi** [comment]
This regression was introduced here https://github.com/apple/swift-syntax/commit/1754a24d6f5aebe39cd066b5d17438621ea02009#diff-aa2c31471e3791a30fa5012a9efa2cb9aab864aa0424bcc76404ded33d7c3e3dL122-L129
