### ISSUE TITLE
Build errors with recent SwiftSyntax versions

### ISSUE THREAD

**Issue by jpsim** [apple/swift-syntax#749]
Is there a special way to build a toolchain that compiles these symbols? Failing as of d538760dba4818cc9a4daa96e953ba19b2642e6f

```
Undefined symbol: _swiftparse_parser_set_enable_bare_slash_regex_literal
Undefined symbol: _swiftparse_parser_set_language_version
```

When building with Xcode 14RC1 or the latest dev toolchain from swift.org.

**Comment by ahoppen** [comment]
rdar://99709025

**Comment by CodaFi** [comment]
I hit this every so often too. It's because we're finding them in the associated internal syntax parsing library in the toolchain. A weak solution here is to guard the usage of those symbols on the compiler version.

**Comment by ahoppen** [comment]
Independent of @CodaFi’s workaround, I think you shouldn’t have this issue with more recent Xcode 14 betas.

**Comment by jpsim** [comment]
> I think you shouldn’t have this issue with more recent Xcode 14 betas.

This was with Xcode 14 Release Candidate 1 (14A309). There is no more recent Xcode beta.

It may have something to do with the Xcode RC having the macOS 12.3 SDK, not macOS 13.

> Xcode 14 RC includes Swift 5.7 and SDKs for iOS 16, iPadOS 16, tvOS 16, watchOS 9, and macOS Monterey 12.5. The Xcode 14 Release Candidate supports on-device debugging in iOS 11 and later, tvOS 11 and later, and watchOS 4 and later. Xcode 14 RC requires a Mac running macOS Monterey 12.5 or later.

Source: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

**Comment by jpsim** [comment]
It looks like this is fixed with the Xcode 14 RC1, but still fails with the most recent toolchain (swift-DEVELOPMENT-SNAPSHOT-2022-09-06-a).

**Comment by ahoppen** [comment]
I just tried with Xcode 14.0.1 (14A400) and swift-DEVELOPMENT-SNAPSHOT-2022-09-12-a and SwiftSyntax builds fine for me. Which configuration isn’t working for you?

**Comment by capnslipp** [comment]
For me, was broken on Xcode 14.0 (14A309) on swift-5.7-RELEASE (current head of swift/5.7 branch); is now fixed with Xcode 14.0.1 RC (14A400).

**Comment by mrstegeman** [comment]
Seeing it when trying to build in Ubuntu 22.04 for Homebrew:

https://github.com/Homebrew/homebrew-core/actions/runs/3095751529/jobs/5010578616

**Comment by ahoppen** [comment]
Which Swift version are you using to build SwiftSyntax? Building 0.50700.0 with Swift 5.6 is not supported.

It’s building fine for me using the following commands.
```
docker run -it --rm swift:5.7-jammy
# Inside docker container
git clone https://github.com/apple/swift-syntax.git
cd swift-syntax
git checkout 0.50700.0
swift build
```

**Comment by mrstegeman** [comment]
Thanks for the tip, I think it's probably running 5.6.3.

**Comment by ahoppen** [comment]
@jpsim Are you still having issue with building swift-syntax? AFAICT all issues have been resolved. If so, could you close this bug?

**Comment by jpsim** [comment]
@ahoppen i believe https://github.com/apple/swift-syntax/pull/752 needs to be applied to the 5.7 release as I’ve mentioned in that PR.

**Comment by ahoppen** [comment]
Since we are now finishing up the 5.8 release and won’t be making any changes to 5.7 anymore, I’m closing this issue. If you think it still applies, feel free to re-open.
