### ISSUE TITLE
Please create 0.50700.0 release

### ISSUE THREAD

**Issue by allevato** [apple/swift-syntax#787]
### Description

Now that Xcode 14 is released, can we please tag 0.50700.0 for semver clients?

**Comment by Jeehut** [comment]
It's been a week now, there are tools depending on this such as [BartyCrouch](https://github.com/FlineDev/BartyCrouch) or [Sitrep](https://github.com/twostraws/Sitrep).
Please make a new release so we can update these tools to work with Xcode 14. Thank you!

**Comment by ahoppen** [comment]
The 0.50700.0 release has now been published: https://github.com/apple/swift-syntax/releases/tag/0.50700.0
