### ISSUE TITLE
`if-let` shorthand syntax is broken when formatting in 0.50700.0

### ISSUE THREAD

**Issue by shimastripe** [apple/swift-syntax#816]
### Description

- In [swift-format@0.50700.0](https://github.com/apple/swift-format/releases/tag/0.50700.0), the unrecognized error is occured in [SE-0345](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md) syntax.
- It looks like it was addressed in https://github.com/apple/swift-syntax/pull/494 , is it not included in 0.50700.0?
- If this is not to ask here, please Close.

### Steps to Reproduce

```swift
struct Example {
  var props: String?

  func check() {
    if let props {
      print(props)
    }
  }
}

Example().check()
```

- When this file is formatting, the below error is occured.
- `Example.swift:5:5: error: file contains invalid or unrecognized Swift syntax.`

**Comment by ahoppen** [comment]
rdar://100186819

**Comment by ahoppen** [comment]
I just created a 0.50700.1 release of SwiftSyntax that parses shorthand `if let` correctly. 

The 0.50700.1 should work out of the box on macOS. On Linux, you will need to use a recent [swift-5.7-DEVELOPMENT-SNAPSHOT](https://www.swift.org/download/#swift-57-development) that’s compatible with this SwiftSyntax release.
