### ISSUE TITLE
CONTRIBUTING.md needs to be updated

### ISSUE THREAD

**Issue by ibrahimoktay** [apple/swift-syntax#841]
### Description

I am not sure if we should call it bug but feel free to change it.
I tried to follow steps in CONTRIBUTING.md and failed.

Here is the error;
```
** Building SwiftSyntax **
error: the package at '/Users/io/Git/dev/swift-argument-parser' cannot be accessed (Error Domain=NSCocoaErrorDomain Code=260 "The folder “swift-argument-parser” doesn’t exist." UserInfo={NSFilePath=/Users/io/Git/dev/swift-argument-parser, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x600000ebee20 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}})
FAIL: Building SwiftSyntax failed
Executing: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2022-09-12-a.xctoolchain/usr/bin/swift build --package-path /Users/io/Git/dev/swift-syntax --product SwiftSyntax
```
How to fix:
- Add swift-argument-parser too in the same folder. (Step 1)

Generate xcodeproj 
`swift package generate-xcodeproj` is deprecated and no longer available. 

Addition:
I think it might be a good idea to add the following line before step 5 in CONTRIBUTING.md as well if you haven't previously installed these tools. 
- `brew install cmake ninja sccache`

### Steps to Reproduce

Follow CONTRIBUTING.md steps.

**Comment by ahoppen** [comment]
rdar://100415842
