### ISSUE TITLE
Parse tree regression in return statement for void function

### ISSUE THREAD

**Issue by jpsim** [apple/swift-syntax#851]
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
final class SearchMessagesDataSource: ValueCellDataSource {
  internal enum Section: Int {
    case emptyState
    case messageThreads
  }

  internal func load(messageThreads: [MessageThread]) {
    self.set(
      values: messageThreads,
      cellClass: MessageThreadCell.self,
      inSection: Section.messageThreads.rawValue
    )
  }

  internal func emptyState(isVisible: Bool) {
    self.set(
      cellIdentifiers: isVisible ? ["SearchMessagesEmptyState"] : [],
      inSection: Section.emptyState.rawValue
    )
  }

  internal override func configureCell(tableCell cell: UITableViewCell, withValue value: Any) {
    switch (cell, value) {
    case let (cell as MessageThreadCell, value as MessageThread):
      cell.configureWith(value: value)
    case (is StaticTableViewCell, is Void):
      return
    default:
      assertionFailure("Unrecognized combo: \(cell), \(value).")
    }
  }
}
```

### Description

SwiftSyntax @ 0.50700.0 : [before.txt](https://github.com/apple/swift-syntax/files/9660925/before.txt)

SwiftSyntax @ 322559c794d7d4ed4d3053c6fac4890941abb0b4 : [after.txt](https://github.com/apple/swift-syntax/files/9660928/after.txt)

So with the 5.7 release, the `ReturnStmtSyntax.expression` is `nil` but with the SwiftParser it's a `MissingExprSyntax`.

|5.7 Parser|Swift Parser|
|-|-|
|<img width="675" alt="image" src="https://user-images.githubusercontent.com/474794/192673945-39e985e9-4aa4-4dc6-adb9-c09ef0a889f6.png">|<img width="665" alt="image" src="https://user-images.githubusercontent.com/474794/192673992-e58d015d-d9fd-424c-b11d-4a005bf12067.png">|

**Comment by ahoppen** [comment]
rdar://100487964

**Comment by jpsim** [comment]
Fixed by https://github.com/apple/swift-syntax/pull/842
