### ISSUE TITLE
KeyPath with space produces a diagnostic

### ISSUE THREAD

**Issue by jpsim** [apple/swift-syntax#888]
### Issue Kind

Parse of Valid Source Produced Invalid Syntax Tree

### Source Code

```swift
_ = distinctUntilChanged(\ .?.status)
```

### Description

The `\ .?.status` keypath should be parsed as a keypath, just like `\.?.status` would be.

Currently producing a diagnostic with 4f2e1537f39583f635d4a343128749d650157537:

> unexpected text '.?.status' in function call

**Comment by ahoppen** [comment]
rdar://100871146

**Comment by jpsim** [comment]
Thanks for the fix!
