### ISSUE TITLE
Swift Parser memory usage is 2x to 4x higher than the previous parser

### ISSUE THREAD

**Issue by jpsim** [apple/swift-syntax#921]
### Description

In one benchmark that effectively just calls `Parser.parse(...)` over a few hundred Swift files, the parser from the Swift 5.7 release consumed up to 19.7 MB, whereas the new Swift Parser from `main` this morning consumed up to 71.5 MB.

### Steps to Reproduce

Grab a recent Firefox iOS release:

```bash
#!/bin/bash

set -euo pipefail

temp_dir="$(mktemp -d)"
echo "$temp_dir" > parse-dir.txt
git clone https://github.com/mozilla-mobile/firefox-ios.git "${temp_dir}"
cd "${temp_dir}"
echo "Checking out branch"
git -c advice.detachedHead=false checkout -q 105.0
echo "Generating list of Swift files"
git ls-files | grep "\.swift$" > swift-files.txt
```

This creates two files:

* `parse-dir.txt` which contains the directory path where the files to parse are located
* `swift-files.txt` which lists all the Swift files to parse within that directory

Then with the `.package(name: "SwiftSyntax", url: "https://github.com/apple/swift-syntax.git", .exact("0.50700.0"))` dependency, run the following script Swift CLI executable:

```swift
import Dispatch
import Foundation
import SwiftSyntaxParser

@main
public struct Main {
    public static func main() throws {
        // Switch to directory with files to parse
        let directory = try String(contentsOfFile: "parse-dir.txt")
            .split(separator: "\n")[0]
        FileManager.default.changeCurrentDirectoryPath(String(directory))

        // Parse all Swift files
        let files = try String(contentsOfFile: "swift-files.txt")
            .split(separator: "\n")
        _ = files.parallelMap { file in
            return autoreleasepool {
                try! SyntaxParser.parse(source: String(contentsOfFile: String(file)))
            }
        }

        // Report memory usage
        print("Done!")
    }
}

extension Array {
    func parallelMap<T>(transform: (Element) -> T) -> [T] {
        var result = ContiguousArray<T?>(repeating: nil, count: count)
        return result.withUnsafeMutableBufferPointer { buffer in
            DispatchQueue.concurrentPerform(iterations: buffer.count) { idx in
                buffer[idx] = transform(self[idx])
            }
            return buffer.map { $0! }
        }
    }
}
```

I'm running it in Xcode 14 (14A309), open it with `xed .`, set the scheme to build with the "Release" build configuration, set a breakpoint on the `print("Done!")` line and note the memory used in Xcode's left pane.

Repeat with SwiftSyntax checked out at 1834d644dcbbbb34df697581435555655bb94e8a, using the parser from the SwiftParser module.

For 5 runs of the 5.7 parser I got the following memory usage measurements: 19.4 MB, 19.7 MB, 19.5 MB, 19.2 MB, 19.3 MB.
For 5 runs of the Swift parser I got the following memory usage measurements: 47.8 MB, 55.5 MB, 71.5 MB, 47.0 MB, 47.4 MB.

Here's a sample project that demonstrates the issue: [swift-syntax-bench.zip](https://github.com/apple/swift-syntax/files/9756886/swift-syntax-bench.zip)

Please let me know if I'm doing something wrong on my end, or if there are any suggestions you might have that could help me reclaim memory after I no longer need a parse tree.

**Comment by ahoppen** [comment]
rdar://101031495

**Comment by jpsim** [comment]
Addressed by https://github.com/apple/swift-syntax/pull/1050
